; --------------------------------
; Ranking 1: Play time when last entered the Hall of Fame
DEF RANKING_GAME_TIME_HOF_ADDR EQUS "sTrainerRankingGameTimeHOFHours"
DEF RANKING_GAME_TIME_HOF_ADDR_MIN EQUS "sTrainerRankingGameTimeHOFMinutes"
DEF RANKING_GAME_TIME_HOF_ADDR_SEC EQUS "sTrainerRankingGameTimeHOFSeconds"
DEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $0016, PRINTNUM_LEADINGZEROS | 1, 2\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $0017, PRINTNUM_LEADINGZEROS | 1, 2"

; variant excluding seconds
;DEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $0016, PRINTNUM_LEADINGZEROS | 1, 2"
DEF RANKING_GAME_TIME_HOF_FMT_PLAYER EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_number {RANKING_GAME_TIME_HOF_ADDR_MIN}, PRINTNUM_LEADINGZEROS | 1, 2\nnts_end\ndb $6D\nnts_start\nnts_number {RANKING_GAME_TIME_HOF_ADDR_SEC}, PRINTNUM_LEADINGZEROS | 1, 2"
DEF RANKING_GAME_TIME_HOF_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
REDEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $001A, PRINTNUM_LEADINGZEROS | 1, 2\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $001A, PRINTNUM_LEADINGZEROS | 1, 2"
; variant excluding seconds
;REDEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $001A, PRINTNUM_LEADINGZEROS | 1, 2"
MACRO describe_ranking_GAME_TIME_HOF
	db   "?"
ENDM
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""

; English
ELIF DEF(_LANG_E)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "LAST HOF RECORD"
MACRO describe_ranking_GAME_TIME_HOF
	para "?"
ENDM
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""

; German
ELIF DEF(_LANG_D)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "SPIELZEIT BEI RH."
MACRO describe_ranking_GAME_TIME_HOF
	para "?"
ENDM
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""

; French
ELIF DEF(_LANG_F)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
MACRO describe_ranking_GAME_TIME_HOF
	para "?"
ENDM
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
MACRO describe_ranking_GAME_TIME_HOF
	para "?"
ENDM
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
MACRO describe_ranking_GAME_TIME_HOF
	para "?"
ENDM
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""
ENDC


; --------------------------------
; Ranking 2: Step count when last entered the Hall of Fame
DEF RANKING_STEP_COUNT_HOF_ADDR EQUS "sTrainerRankingStepCountHOF"
DEF RANKING_STEP_COUNT_HOF_FMT  EQUS "4, 9"
DEF RANKING_STEP_COUNT_HOF_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT_HOF
	db   "?"
ENDM
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS ""

; English
ELIF DEF(_LANG_E)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "LAST HOF STEPS"
MACRO describe_ranking_STEP_COUNT_HOF
	para "?"
ENDM
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS " steps"
REDEF RANKING_STEP_COUNT_HOF_SPACING EQU -1

; German
ELIF DEF(_LANG_D)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "SCHRITTE BEI RH."
MACRO describe_ranking_STEP_COUNT_HOF
	para "?"
ENDM
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"

; French
ELIF DEF(_LANG_F)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT_HOF
	para "?"
ENDM
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT_HOF
	para "?"
ENDM
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT_HOF
	para "?"
ENDM
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 3: Number of times the party was healed when last entered the Hall of Fame
DEF RANKING_HEALINGS_HOF_ADDR EQUS "sTrainerRankingHealingsHOF"
DEF RANKING_HEALINGS_HOF_FMT  EQUS "4, 9"
DEF RANKING_HEALINGS_HOF_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
MACRO describe_ranking_HEALINGS_HOF
	db   "?"
ENDM
DEF RANKING_HEALINGS_HOF_UNIT EQUS ""

; English
ELIF DEF(_LANG_E)
DEF RANKING_HEALINGS_HOF_NAME EQUS "LAST HOF HEALED"
MACRO describe_ranking_HEALINGS_HOF
	para "?"
ENDM
DEF RANKING_HEALINGS_HOF_UNIT EQUS " heals"
REDEF RANKING_HEALINGS_HOF_SPACING EQU 1

; German
ELIF DEF(_LANG_D)
DEF RANKING_HEALINGS_HOF_NAME EQUS "TEAM-HEILUNGEN BEI RH."
MACRO describe_ranking_HEALINGS_HOF
	para "?"
ENDM
DEF RANKING_HEALINGS_HOF_UNIT EQUS " Heilungen"
REDEF RANKING_HEALINGS_HOF_SPACING EQU -3

; French
ELIF DEF(_LANG_F)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
MACRO describe_ranking_HEALINGS_HOF
	para "?"
ENDM
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
MACRO describe_ranking_HEALINGS_HOF
	para "?"
ENDM
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
MACRO describe_ranking_HEALINGS_HOF
	para "?"
ENDM
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 4: Number of battles when last entered the Hall of Fame
; Copies from Ranking 8 during hall of fame sequence
; INCLUDES:
; - wild battles
; - trainer battles
; - bug contest battles
; - link battles
; - other battle types im forgetting
; EXCLUDES:
; - catching tutorial
DEF RANKING_BATTLES_HOF_ADDR EQUS "sTrainerRankingBattlesHOF"
DEF RANKING_BATTLES_HOF_FMT  EQUS "3, 7"
DEF RANKING_BATTLES_HOF_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
MACRO describe_ranking_BATTLES_HOF
	db   "?"
ENDM
DEF RANKING_BATTLES_HOF_UNIT EQUS "かい" ; a guess

; English
ELIF DEF(_LANG_E)
DEF RANKING_BATTLES_HOF_NAME EQUS "LAST HOF BATTLES"
MACRO describe_ranking_BATTLES_HOF
	para "?"
ENDM
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"

; German
ELIF DEF(_LANG_D)
DEF RANKING_BATTLES_HOF_NAME EQUS "KÄMPFE BEI RH."
MACRO describe_ranking_BATTLES_HOF
	para "?"
ENDM
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"

; French
ELIF DEF(_LANG_F)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
MACRO describe_ranking_BATTLES_HOF
	para "?"
ENDM
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
MACRO describe_ranking_BATTLES_HOF
	para "?"
ENDM
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
MACRO describe_ranking_BATTLES_HOF
	para "?"
ENDM
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 5: Step count
DEF RANKING_STEP_COUNT_ADDR EQUS "sTrainerRankingStepCount"
DEF RANKING_STEP_COUNT_FMT  EQUS "4, 9"
DEF RANKING_STEP_COUNT_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT
	db   "?"
ENDM
DEF RANKING_STEP_COUNT_UNIT EQUS ""

; English
ELIF DEF(_LANG_E)
DEF RANKING_STEP_COUNT_NAME EQUS "STEPS WALKED"
MACRO describe_ranking_STEP_COUNT
	para "?"
ENDM
DEF RANKING_STEP_COUNT_UNIT EQUS " steps"
REDEF RANKING_STEP_COUNT_SPACING EQU -1

; German
ELIF DEF(_LANG_D)
DEF RANKING_STEP_COUNT_NAME EQUS "SCHRITTE GELAUFEN"
MACRO describe_ranking_STEP_COUNT
	para "?"
ENDM
DEF RANKING_STEP_COUNT_UNIT EQUS "?"

; French
ELIF DEF(_LANG_F)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT
	para "?"
ENDM
DEF RANKING_STEP_COUNT_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT
	para "?"
ENDM
DEF RANKING_STEP_COUNT_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
MACRO describe_ranking_STEP_COUNT
	para "?"
ENDM
DEF RANKING_STEP_COUNT_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 6: Number of Battle Tower Wins
DEF RANKING_BATTLE_TOWER_WINS_ADDR EQUS "sTrainerRankingBattleTowerWins"
; 2, 5, SPACING=1 matches. 4, (6 or 7) works
;DEF RANKING_BATTLE_TOWER_WINS_FMT  EQUS "2, 5"
DEF RANKING_BATTLE_TOWER_WINS_FMT  EQUS "4, 7"
DEF RANKING_BATTLE_TOWER_WINS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "バトルタワーで　かった　かいすう"
MACRO describe_ranking_BATTLE_TOWER_WINS
	db   "４０ばんどうろ<NO>バトルタワーで"
	cont "あなた<GA>これまで<NI>なんにんの"
	cont "<TRAINER>と<NO>しょうぶ<NI>かったか"
	cont "にんずうで　きそいます"
ENDM
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "BATTLE TOWER WINS"
MACRO describe_ranking_BATTLE_TOWER_WINS
	para "The number of"
	line "#MON battles"
	cont "won against other"
	cont "<TRAINER>S at the"
	cont "BATTLE TOWER on"
	cont "ROUTE 40."
ENDM
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " wins"
REDEF RANKING_BATTLE_TOWER_WINS_SPACING EQU 2
; Rework in other languages (?)

; German
ELIF DEF(_LANG_D)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "DUELLTURM"
MACRO describe_ranking_BATTLE_TOWER_WINS
	para "Die Anzahl der"
	line "gewonnenen"
	cont "#MON-Kämpfe"
	cont "gegen andere"
	cont "<TRAINER> beim"
	cont "DUELLTURM auf"
	cont "ROUTE 40."
ENDM
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " Punkte"
REDEF RANKING_BATTLE_TOWER_WINS_SPACING EQU 0

; French
ELIF DEF(_LANG_F)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "TOUR DE COMBAT"
MACRO describe_ranking_BATTLE_TOWER_WINS
	para "Nombre de"
	line "combats #MON"
	cont "gagnés contre les"
	cont "<TRAINER>S dans"
	cont "la TOUR de COMBAT"
	cont "sur la ROUTE 40."
ENDM
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " points"
REDEF RANKING_BATTLE_TOWER_WINS_SPACING EQU 0

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "TORRE LOTTA"
MACRO describe_ranking_BATTLE_TOWER_WINS
	para "Il numero di lotte"
	line "#MON vinte"
	cont "contro gli"
	cont "ALLENATORI alla"
	cont "TORRE LOTTA sul"
	cont "PERCORSO 40."
ENDM
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " punti"
REDEF RANKING_BATTLE_TOWER_WINS_SPACING EQU 1

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "?"
MACRO describe_ranking_BATTLE_TOWER_WINS
	para "?"
ENDM
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 7: Number of times TMs and HMs have been taught
DEF RANKING_TMS_HMS_TAUGHT_ADDR EQUS "sTrainerRankingTMsHMsTaught"
DEF RANKING_TMS_HMS_TAUGHT_FMT  EQUS "3, 7"
DEF RANKING_TMS_HMS_TAUGHT_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
MACRO describe_ranking_TMS_HMS_TAUGHT
	db   "?"
ENDM
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "TMs/HMs TAUGHT"
MACRO describe_ranking_TMS_HMS_TAUGHT
	para "?"
ENDM
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS " taught"

; German
ELIF DEF(_LANG_D)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "TMs/VMs-EINSATZ"
MACRO describe_ranking_TMS_HMS_TAUGHT
	para "?"
ENDM
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS " eingesetzt"

; French
ELIF DEF(_LANG_F)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
MACRO describe_ranking_TMS_HMS_TAUGHT
	para "?"
ENDM
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
MACRO describe_ranking_TMS_HMS_TAUGHT
	para "?"
ENDM
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
MACRO describe_ranking_TMS_HMS_TAUGHT
	para "?"
ENDM
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 8: Number of battles
; incremented during `BattleIntro`
; INCLUDES:
; - wild battles
; - trainer battles
; - bug contest battles
; - link battles
; - other battle types im forgetting
; SPECIFICALLY EXCLUDES:
; - catching tutorial
DEF RANKING_BATTLES_ADDR EQUS "sTrainerRankingBattles"
DEF RANKING_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_BATTLES_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_BATTLES_NAME EQUS "ポケモンと　たたかった　かいすう"
MACRO describe_ranking_BATTLES
	db   "?"
ENDM
DEF RANKING_BATTLES_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_BATTLES_NAME EQUS "#MON BATTLES"
MACRO describe_ranking_BATTLES
	para "?"
ENDM
DEF RANKING_BATTLES_UNIT EQUS " battles"

; German
ELIF DEF(_LANG_D)
DEF RANKING_BATTLES_NAME EQUS "#MON-KÄMPFE"
MACRO describe_ranking_BATTLES
	para "?"
ENDM
DEF RANKING_BATTLES_UNIT EQUS " Kämpfe"

; French
ELIF DEF(_LANG_F)
DEF RANKING_BATTLES_NAME EQUS "?"
MACRO describe_ranking_BATTLES
	para "?"
ENDM
DEF RANKING_BATTLES_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_BATTLES_NAME EQUS "?"
MACRO describe_ranking_BATTLES
	para "?"
ENDM
DEF RANKING_BATTLES_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_BATTLES_NAME EQUS "?"
MACRO describe_ranking_BATTLES
	para "?"
ENDM
DEF RANKING_BATTLES_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 9: Number of wild Pokémon battles
; incremented during `InitEnemyWildmon`
; INCLUDES
; - wild battles
; - bug contest battles
; EXCLUDES:
; - catching tutorial
; - trainer battles
; - link battles
DEF RANKING_WILD_BATTLES_ADDR EQUS "sTrainerRankingWildBattles"
DEF RANKING_WILD_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_WILD_BATTLES_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
MACRO describe_ranking_WILD_BATTLES
	db   "?"
ENDM
DEF RANKING_WILD_BATTLES_UNIT EQUS "かい" ; a guess

; English
ELIF DEF(_LANG_E)
DEF RANKING_WILD_BATTLES_NAME EQUS "#MON ENCOUNTER"
MACRO describe_ranking_WILD_BATTLES
	para "?"
ENDM
DEF RANKING_WILD_BATTLES_UNIT EQUS " times"

; German
ELIF DEF(_LANG_D)
DEF RANKING_WILD_BATTLES_NAME EQUS "#MON BEGEGNET"
MACRO describe_ranking_WILD_BATTLES
	para "?"
ENDM
DEF RANKING_WILD_BATTLES_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
MACRO describe_ranking_WILD_BATTLES
	para "?"
ENDM
DEF RANKING_WILD_BATTLES_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
MACRO describe_ranking_WILD_BATTLES
	para "?"
ENDM
DEF RANKING_WILD_BATTLES_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
MACRO describe_ranking_WILD_BATTLES
	para "?"
ENDM
DEF RANKING_WILD_BATTLES_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 10: Number of Trainer battles
; incremented during `InitEnemyTrainer`
; INCLUDES
; - trainer battles
; - link battles
; EXCLUDES:
; - catching tutorial
; - wild battles
; - bug contest battles
DEF RANKING_TRAINER_BATTLES_ADDR EQUS "sTrainerRankingTrainerBattles"
DEF RANKING_TRAINER_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_TRAINER_BATTLES_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
MACRO describe_ranking_TRAINER_BATTLES
	db   "?"
ENDM
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "かい" ; a guess

; English
ELIF DEF(_LANG_E)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "<TRAINER> BATTLES"
MACRO describe_ranking_TRAINER_BATTLES
	para "?"
ENDM
DEF RANKING_TRAINER_BATTLES_UNIT EQUS " battles"

; German
ELIF DEF(_LANG_D)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "<TRAINER>-KÄMPFE"
MACRO describe_ranking_TRAINER_BATTLES
	para "?"
ENDM
DEF RANKING_TRAINER_BATTLES_UNIT EQUS " Kämpfe"

; French
ELIF DEF(_LANG_F)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
MACRO describe_ranking_TRAINER_BATTLES
	para "?"
ENDM
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
MACRO describe_ranking_TRAINER_BATTLES
	para "?"
ENDM
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
MACRO describe_ranking_TRAINER_BATTLES
	para "?"
ENDM
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 11: Unused 1
DEF RANKING_UNUSED_1_ADDR EQUS "sTrainerRankingUnused1"
DEF RANKING_UNUSED_1_FMT  EQUS "3, 8"
DEF RANKING_UNUSED_1_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_UNUSED_1_NAME EQUS "?"
MACRO describe_ranking_UNUSED_1
	db   "?"
ENDM
DEF RANKING_UNUSED_1_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_UNUSED_1_NAME EQUS "?"
MACRO describe_ranking_UNUSED_1
	para "?"
ENDM
DEF RANKING_UNUSED_1_UNIT EQUS "?"

; German
ELIF DEF(_LANG_D)
DEF RANKING_UNUSED_1_NAME EQUS "?"
MACRO describe_ranking_UNUSED_1
	para "?"
ENDM
DEF RANKING_UNUSED_1_UNIT EQUS "?"

; French
ELIF DEF(_LANG_F)
DEF RANKING_UNUSED_1_NAME EQUS "?"
MACRO describe_ranking_UNUSED_1
	para "?"
ENDM
DEF RANKING_UNUSED_1_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_UNUSED_1_NAME EQUS "?"
MACRO describe_ranking_UNUSED_1
	para "?"
ENDM
DEF RANKING_UNUSED_1_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_UNUSED_1_NAME EQUS "?"
MACRO describe_ranking_UNUSED_1
	para "?"
ENDM
DEF RANKING_UNUSED_1_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 12: Number of Hall of Fame inductions
DEF RANKING_HOF_ENTRIES_ADDR EQUS "sTrainerRankingHOFEntries"
DEF RANKING_HOF_ENTRIES_FMT  EQUS "3, 7"
DEF RANKING_HOF_ENTRIES_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
MACRO describe_ranking_HOF_ENTRIES
	db   "?"
ENDM
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_HOF_ENTRIES_NAME EQUS "HOF ENTRIES"
MACRO describe_ranking_HOF_ENTRIES
	para "?"
ENDM
DEF RANKING_HOF_ENTRIES_UNIT EQUS " entries"

; German
ELIF DEF(_LANG_D)
DEF RANKING_HOF_ENTRIES_NAME EQUS "RUHMESHALLENEINTR."
MACRO describe_ranking_HOF_ENTRIES
	para "?"
ENDM
DEF RANKING_HOF_ENTRIES_UNIT EQUS " Einträge"

; French
ELIF DEF(_LANG_F)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
MACRO describe_ranking_HOF_ENTRIES
	para "?"
ENDM
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
MACRO describe_ranking_HOF_ENTRIES
	para "?"
ENDM
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
MACRO describe_ranking_HOF_ENTRIES
	para "?"
ENDM
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 13: Number of wild Pokémon caught
DEF RANKING_WILD_MONS_CAUGHT_ADDR EQUS "sTrainerRankingWildMonsCaught"
DEF RANKING_WILD_MONS_CAUGHT_FMT  EQUS "3, 7"
DEF RANKING_WILD_MONS_CAUGHT_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "つかまえた　ポケモンの　かず"
MACRO describe_ranking_WILD_MONS_CAUGHT
	db   "?"
ENDM
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "ひき"

; English
ELIF DEF(_LANG_E)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "#MON CAUGHT"
MACRO describe_ranking_WILD_MONS_CAUGHT
	para "?"
ENDM
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS " caught"

; German
ELIF DEF(_LANG_D)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "#MON GEFANGEN"
MACRO describe_ranking_WILD_MONS_CAUGHT
	para "?"
ENDM
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS " gefangen"

; French
ELIF DEF(_LANG_F)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "?"
MACRO describe_ranking_WILD_MONS_CAUGHT
	para "?"
ENDM
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "?"
MACRO describe_ranking_WILD_MONS_CAUGHT
	para "?"
ENDM
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "?"
MACRO describe_ranking_WILD_MONS_CAUGHT
	para "?"
ENDM
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 14: Number of hooked Pokémon encounters
DEF RANKING_HOOKED_ENCOUNTERS_ADDR EQUS "sTrainerRankingHookedEncounters"
DEF RANKING_HOOKED_ENCOUNTERS_FMT  EQUS "3, 7"
DEF RANKING_HOOKED_ENCOUNTERS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "ポケモンを　つった　かいすう"
MACRO describe_ranking_HOOKED_ENCOUNTERS
	db   "?"
ENDM
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "#MON HOOKED"
MACRO describe_ranking_HOOKED_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS " hooked"

; German
ELIF DEF(_LANG_D)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "#MON GEANGELT"
MACRO describe_ranking_HOOKED_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS " geangelt"

; French
ELIF DEF(_LANG_F)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "?"
MACRO describe_ranking_HOOKED_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "?"
MACRO describe_ranking_HOOKED_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "?"
MACRO describe_ranking_HOOKED_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 15: Number of Eggs hatched
DEF RANKING_EGGS_HATCHED_ADDR EQUS "sTrainerRankingEggsHatched"
DEF RANKING_EGGS_HATCHED_FMT  EQUS "3, 7"
DEF RANKING_EGGS_HATCHED_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_EGGS_HATCHED_NAME EQUS "タマゴを　かえした　かいすう"
MACRO describe_ranking_EGGS_HATCHED
	db   "?"
ENDM
DEF RANKING_EGGS_HATCHED_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_EGGS_HATCHED_NAME EQUS "EGGS HATCHED"
MACRO describe_ranking_EGGS_HATCHED
	para "?"
ENDM
DEF RANKING_EGGS_HATCHED_UNIT EQUS " EGGS"

; German
ELIF DEF(_LANG_D)
DEF RANKING_EGGS_HATCHED_NAME EQUS "EIER GESCHLÜPFT"
MACRO describe_ranking_EGGS_HATCHED
	para "?"
ENDM
DEF RANKING_EGGS_HATCHED_UNIT EQUS " EIER"

; French
ELIF DEF(_LANG_F)
DEF RANKING_EGGS_HATCHED_NAME EQUS "?"
MACRO describe_ranking_EGGS_HATCHED
	para "?"
ENDM
DEF RANKING_EGGS_HATCHED_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_EGGS_HATCHED_NAME EQUS "?"
MACRO describe_ranking_EGGS_HATCHED
	para "?"
ENDM
DEF RANKING_EGGS_HATCHED_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_EGGS_HATCHED_NAME EQUS "?"
MACRO describe_ranking_EGGS_HATCHED
	para "?"
ENDM
DEF RANKING_EGGS_HATCHED_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 16: Number of Pokémon evolved
DEF RANKING_MONS_EVOLVED_ADDR EQUS "sTrainerRankingMonsEvolved"
DEF RANKING_MONS_EVOLVED_FMT  EQUS "3, 7"
DEF RANKING_MONS_EVOLVED_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_MONS_EVOLVED_NAME EQUS "ポケモンが　しんかした　かいすう"
MACRO describe_ranking_MONS_EVOLVED
	db   "?"
ENDM
DEF RANKING_MONS_EVOLVED_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_MONS_EVOLVED_NAME EQUS "#MON EVOLVED"
MACRO describe_ranking_MONS_EVOLVED
	para "?"
ENDM
DEF RANKING_MONS_EVOLVED_UNIT EQUS " evolved"

; German
ELIF DEF(_LANG_D)
DEF RANKING_MONS_EVOLVED_NAME EQUS "#MON ENTWICKELT"
MACRO describe_ranking_MONS_EVOLVED
	para "?"
ENDM
DEF RANKING_MONS_EVOLVED_UNIT EQUS " entwickelt"

; French
ELIF DEF(_LANG_F)
DEF RANKING_MONS_EVOLVED_NAME EQUS "?"
MACRO describe_ranking_MONS_EVOLVED
	para "?"
ENDM
DEF RANKING_MONS_EVOLVED_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_MONS_EVOLVED_NAME EQUS "?"
MACRO describe_ranking_MONS_EVOLVED
	para "?"
ENDM
DEF RANKING_MONS_EVOLVED_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_MONS_EVOLVED_NAME EQUS "?"
MACRO describe_ranking_MONS_EVOLVED
	para "?"
ENDM
DEF RANKING_MONS_EVOLVED_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 17: Number of Berries and Apricorns picked
; includes any item obtained from a "fruit tree" object
DEF RANKING_FRUIT_PICKED_ADDR EQUS "sTrainerRankingFruitPicked"
DEF RANKING_FRUIT_PICKED_FMT  EQUS "3, 7"
DEF RANKING_FRUIT_PICKED_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_FRUIT_PICKED_NAME EQUS "とった　きのみの　かず"
MACRO describe_ranking_FRUIT_PICKED
	db   "?"
ENDM
DEF RANKING_FRUIT_PICKED_UNIT EQUS "こ"

; English
ELIF DEF(_LANG_E)
; name "FRUIT" was chosen because of the first line
; when interacting with the berry/apricorn tree object:
; "It's a fruit-bearing tree."
DEF RANKING_FRUIT_PICKED_NAME EQUS "FRUIT PICKED"
MACRO describe_ranking_FRUIT_PICKED
	para "?"
ENDM
DEF RANKING_FRUIT_PICKED_UNIT EQUS " fruit"
REDEF RANKING_FRUIT_PICKED_SPACING EQU 1

; German
ELIF DEF(_LANG_D)
DEF RANKING_FRUIT_PICKED_NAME EQUS "OBST GEPFLÜCKT"
MACRO describe_ranking_FRUIT_PICKED
	para "?"
ENDM
DEF RANKING_FRUIT_PICKED_UNIT EQUS " Stück"
REDEF RANKING_FRUIT_PICKED_SPACING EQU 1

; French
ELIF DEF(_LANG_F)
DEF RANKING_FRUIT_PICKED_NAME EQUS "?"
MACRO describe_ranking_FRUIT_PICKED
	para "?"
ENDM
DEF RANKING_FRUIT_PICKED_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_FRUIT_PICKED_NAME EQUS "?"
MACRO describe_ranking_FRUIT_PICKED
	para "?"
ENDM
DEF RANKING_FRUIT_PICKED_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_FRUIT_PICKED_NAME EQUS "?"
MACRO describe_ranking_FRUIT_PICKED
	para "?"
ENDM
DEF RANKING_FRUIT_PICKED_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 18: Number of times the party is healed
; INCLUDES
; - the healing machine in elm's lab
; - sleeping in your cabin in the fast ship
; - being healed before a mobile battle
; - the scene with mr. pokémon and oak at the start of the game
; - the healer on rt. 26
; - lance healing the party in rocket base b2f
; - pokémon center nurse
; - pokécom center nurse
DEF RANKING_HEALINGS_ADDR EQUS "sTrainerRankingHealings"
DEF RANKING_HEALINGS_FMT  EQUS "3, 7"
DEF RANKING_HEALINGS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_HEALINGS_NAME EQUS "?"
MACRO describe_ranking_HEALINGS
	db   "?"
ENDM
DEF RANKING_HEALINGS_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_HEALINGS_NAME EQUS "PARTY HEALED"
MACRO describe_ranking_HEALINGS
	para "?"
ENDM
DEF RANKING_HEALINGS_UNIT EQUS " heals"
REDEF RANKING_HEALINGS_SPACING EQU 1

; German
ELIF DEF(_LANG_D)
DEF RANKING_HEALINGS_NAME EQUS "TEAM GEHEILT"
MACRO describe_ranking_HEALINGS
	para "?"
ENDM
DEF RANKING_HEALINGS_UNIT EQUS " Heilungen"
REDEF RANKING_HEALINGS_SPACING EQU -3

; French
ELIF DEF(_LANG_F)
DEF RANKING_HEALINGS_NAME EQUS "?"
MACRO describe_ranking_HEALINGS
	para "?"
ENDM
DEF RANKING_HEALINGS_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_HEALINGS_NAME EQUS "?"
MACRO describe_ranking_HEALINGS
	para "?"
ENDM
DEF RANKING_HEALINGS_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_HEALINGS_NAME EQUS "?"
MACRO describe_ranking_HEALINGS
	para "?"
ENDM
DEF RANKING_HEALINGS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 19: Number of times Mystery Gift is used
DEF RANKING_MYSTERY_GIFT_ADDR EQUS "sTrainerRankingMysteryGift"
DEF RANKING_MYSTERY_GIFT_FMT  EQUS "3, 7"
DEF RANKING_MYSTERY_GIFT_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "ふしぎな　おくりものの　かいすう"
MACRO describe_ranking_MYSTERY_GIFT
	db   "?"
ENDM
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "MYSTERY GIFT USED"
MACRO describe_ranking_MYSTERY_GIFT
	para "?"
ENDM
DEF RANKING_MYSTERY_GIFT_UNIT EQUS " gifts"
REDEF RANKING_MYSTERY_GIFT_SPACING EQU 1

; German
ELIF DEF(_LANG_D)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "GEHEIMGABE GENUTZT"
MACRO describe_ranking_MYSTERY_GIFT
	para "?"
ENDM
DEF RANKING_MYSTERY_GIFT_UNIT EQUS " Mal"
REDEF RANKING_MYSTERY_GIFT_SPACING EQU 3

; French
ELIF DEF(_LANG_F)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "?"
MACRO describe_ranking_MYSTERY_GIFT
	para "?"
ENDM
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "?"
MACRO describe_ranking_MYSTERY_GIFT
	para "?"
ENDM
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "?"
MACRO describe_ranking_MYSTERY_GIFT
	para "?"
ENDM
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 20: Number of trades
DEF RANKING_TRADES_ADDR EQUS "sTrainerRankingTrades"
DEF RANKING_TRADES_FMT  EQUS "3, 7"
DEF RANKING_TRADES_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_TRADES_NAME EQUS "?"
MACRO describe_ranking_TRADES
	db   "?"
ENDM
DEF RANKING_TRADES_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_TRADES_NAME EQUS "TRADES COMPLETED"
MACRO describe_ranking_TRADES
	para "?"
ENDM
DEF RANKING_TRADES_UNIT EQUS " trades"

; German
ELIF DEF(_LANG_D)
DEF RANKING_TRADES_NAME EQUS "TAUSCHVORGÄNGE"
MACRO describe_ranking_TRADES
	para "?"
ENDM
DEF RANKING_TRADES_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_TRADES_NAME EQUS "?"
MACRO describe_ranking_TRADES
	para "?"
ENDM
DEF RANKING_TRADES_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_TRADES_NAME EQUS "?"
MACRO describe_ranking_TRADES
	para "?"
ENDM
DEF RANKING_TRADES_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_TRADES_NAME EQUS "?"
MACRO describe_ranking_TRADES
	para "?"
ENDM
DEF RANKING_TRADES_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 21: Number of uses of field move Fly
DEF RANKING_FLY_ADDR EQUS "sTrainerRankingFly"
DEF RANKING_FLY_FMT  EQUS "3, 7"
DEF RANKING_FLY_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_FLY_NAME EQUS "?"
MACRO describe_ranking_FLY
	db   "?"
ENDM
DEF RANKING_FLY_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_FLY_NAME EQUS "FLY USED"
MACRO describe_ranking_FLY
	para "?"
ENDM
DEF RANKING_FLY_UNIT EQUS " times"

; German
ELIF DEF(_LANG_D)
DEF RANKING_FLY_NAME EQUS "FLIEGEN-EINSATZ"
MACRO describe_ranking_FLY
	para "?"
ENDM
DEF RANKING_FLY_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_FLY_NAME EQUS "?"
MACRO describe_ranking_FLY
	para "?"
ENDM
DEF RANKING_FLY_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_FLY_NAME EQUS "?"
MACRO describe_ranking_FLY
	para "?"
ENDM
DEF RANKING_FLY_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_FLY_NAME EQUS "?"
MACRO describe_ranking_FLY
	para "?"
ENDM
DEF RANKING_FLY_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 22: Number of uses of field move Surf
DEF RANKING_SURF_ADDR EQUS "sTrainerRankingSurf"
DEF RANKING_SURF_FMT  EQUS "3, 7"
DEF RANKING_SURF_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_SURF_NAME EQUS "?"
MACRO describe_ranking_SURF
	db   "?"
ENDM
DEF RANKING_SURF_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_SURF_NAME EQUS "SURF USED"
MACRO describe_ranking_SURF
	para "?"
ENDM
DEF RANKING_SURF_UNIT EQUS " times"

; German
ELIF DEF(_LANG_D)
DEF RANKING_SURF_NAME EQUS "SURFER-EINSATZ"
MACRO describe_ranking_SURF
	para "?"
ENDM
DEF RANKING_SURF_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_SURF_NAME EQUS "?"
MACRO describe_ranking_SURF
	para "?"
ENDM
DEF RANKING_SURF_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_SURF_NAME EQUS "?"
MACRO describe_ranking_SURF
	para "?"
ENDM
DEF RANKING_SURF_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_SURF_NAME EQUS "?"
MACRO describe_ranking_SURF
	para "?"
ENDM
DEF RANKING_SURF_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 23: Number of uses of field move Waterfall
DEF RANKING_WATERFALL_ADDR EQUS "sTrainerRankingWaterfall"
DEF RANKING_WATERFALL_FMT  EQUS "3, 7"
DEF RANKING_WATERFALL_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_WATERFALL_NAME EQUS "?"
MACRO describe_ranking_WATERFALL
	db   "?"
ENDM
DEF RANKING_WATERFALL_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_WATERFALL_NAME EQUS "WATERFALL USED"
MACRO describe_ranking_WATERFALL
	para "?"
ENDM
DEF RANKING_WATERFALL_UNIT EQUS " times"

; German
ELIF DEF(_LANG_D)
DEF RANKING_WATERFALL_NAME EQUS "KASKADE-EINSATZ"
MACRO describe_ranking_WATERFALL
	para "?"
ENDM
DEF RANKING_WATERFALL_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_WATERFALL_NAME EQUS "?"
MACRO describe_ranking_WATERFALL
	para "?"
ENDM
DEF RANKING_WATERFALL_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_WATERFALL_NAME EQUS "?"
MACRO describe_ranking_WATERFALL
	para "?"
ENDM
DEF RANKING_WATERFALL_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_WATERFALL_NAME EQUS "?"
MACRO describe_ranking_WATERFALL
	para "?"
ENDM
DEF RANKING_WATERFALL_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 24: Number of times the player whited out
DEF RANKING_WHITE_OUTS_ADDR EQUS "sTrainerRankingWhiteOuts"
DEF RANKING_WHITE_OUTS_FMT  EQUS "3, 7"
DEF RANKING_WHITE_OUTS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
MACRO describe_ranking_WHITE_OUTS
	db   "?"
ENDM
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_WHITE_OUTS_NAME EQUS "TIMES WHITED OUT"
MACRO describe_ranking_WHITE_OUTS
	para "?"
ENDM
DEF RANKING_WHITE_OUTS_UNIT EQUS " times"

; German
ELIF DEF(_LANG_D)
DEF RANKING_WHITE_OUTS_NAME EQUS "ANZAHL OHNMÄCHTIG"
MACRO describe_ranking_WHITE_OUTS
	para "?"
ENDM
DEF RANKING_WHITE_OUTS_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
MACRO describe_ranking_WHITE_OUTS
	para "?"
ENDM
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
MACRO describe_ranking_WHITE_OUTS
	para "?"
ENDM
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
MACRO describe_ranking_WHITE_OUTS
	para "?"
ENDM
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 25: Number of Lucky Number Show prizes won
DEF RANKING_LUCKY_NUMBER_SHOW_ADDR EQUS "sTrainerRankingLuckyNumberShow"
DEF RANKING_LUCKY_NUMBER_SHOW_FMT  EQUS "3, 7"
DEF RANKING_LUCKY_NUMBER_SHOW_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
MACRO describe_ranking_LUCKY_NUMBER_SHOW
	db   "?"
ENDM
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "LUCKY NUMBER WINS"
MACRO describe_ranking_LUCKY_NUMBER_SHOW
	para "?"
ENDM
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS " wins"

; German
ELIF DEF(_LANG_D)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "LOTTERIE-GEWINNE"
MACRO describe_ranking_LUCKY_NUMBER_SHOW
	para "?"
ENDM
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS " Gewinne"

; French
ELIF DEF(_LANG_F)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
MACRO describe_ranking_LUCKY_NUMBER_SHOW
	para "?"
ENDM
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
MACRO describe_ranking_LUCKY_NUMBER_SHOW
	para "?"
ENDM
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
MACRO describe_ranking_LUCKY_NUMBER_SHOW
	para "?"
ENDM
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 26: Number of Phone calls made and received
DEF RANKING_PHONE_CALLS_ADDR EQUS "sTrainerRankingPhoneCalls"
DEF RANKING_PHONE_CALLS_FMT  EQUS "3, 7"
DEF RANKING_PHONE_CALLS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
MACRO describe_ranking_PHONE_CALLS
	db   "?"
ENDM
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_PHONE_CALLS_NAME EQUS "TOTAL PHONE CALLS"
MACRO describe_ranking_PHONE_CALLS
	para "?"
ENDM
DEF RANKING_PHONE_CALLS_UNIT EQUS " calls"

; German
ELIF DEF(_LANG_D)
DEF RANKING_PHONE_CALLS_NAME EQUS "GESAMTZAHL ANRUFE"
MACRO describe_ranking_PHONE_CALLS
	para "?"
ENDM
DEF RANKING_PHONE_CALLS_UNIT EQUS " Anrufe"

; French
ELIF DEF(_LANG_F)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
MACRO describe_ranking_PHONE_CALLS
	para "?"
ENDM
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
MACRO describe_ranking_PHONE_CALLS
	para "?"
ENDM
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
MACRO describe_ranking_PHONE_CALLS
	para "?"
ENDM
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 27: Unused 2
DEF RANKING_UNUSED_2_ADDR EQUS "sTrainerRankingUnused2"
DEF RANKING_UNUSED_2_FMT  EQUS "3, 8"
DEF RANKING_UNUSED_2_SPACING EQU 1

; Japanese
IF DEF(_LANG_J)
DEF RANKING_UNUSED_2_NAME EQUS "?"
MACRO describe_ranking_UNUSED_2
	db   "?"
ENDM
DEF RANKING_UNUSED_2_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_UNUSED_2_NAME EQUS "?"
MACRO describe_ranking_UNUSED_2
	para "?"
ENDM
DEF RANKING_UNUSED_2_UNIT EQUS "?"

; German
ELIF DEF(_LANG_D)
DEF RANKING_UNUSED_2_NAME EQUS "?"
MACRO describe_ranking_UNUSED_2
	para "?"
ENDM
DEF RANKING_UNUSED_2_UNIT EQUS "?"

; French
ELIF DEF(_LANG_F)
DEF RANKING_UNUSED_2_NAME EQUS "?"
MACRO describe_ranking_UNUSED_2
	para "?"
ENDM
DEF RANKING_UNUSED_2_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_UNUSED_2_NAME EQUS "?"
MACRO describe_ranking_UNUSED_2
	para "?"
ENDM
DEF RANKING_UNUSED_2_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_UNUSED_2_NAME EQUS "?"
MACRO describe_ranking_UNUSED_2
	para "?"
ENDM
DEF RANKING_UNUSED_2_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 28: Number of Colosseum battles
DEF RANKING_LINK_BATTLES_ADDR EQUS "sTrainerRankingLinkBattles"
DEF RANKING_LINK_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_LINK_BATTLES_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
MACRO describe_ranking_LINK_BATTLES
	db   "?"
ENDM
DEF RANKING_LINK_BATTLES_UNIT EQUS "かい" ; a guess

; English
ELIF DEF(_LANG_E)
DEF RANKING_LINK_BATTLES_NAME EQUS "COLOSSEUM BATTLES"
MACRO describe_ranking_LINK_BATTLES
	para "?"
ENDM
DEF RANKING_LINK_BATTLES_UNIT EQUS " battles"

; German
ELIF DEF(_LANG_D)
DEF RANKING_LINK_BATTLES_NAME EQUS "KOLOSSEUM-KÄMPFE"
MACRO describe_ranking_LINK_BATTLES
	para "?"
ENDM
DEF RANKING_LINK_BATTLES_UNIT EQUS " Kämpfe"

; French
ELIF DEF(_LANG_F)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
MACRO describe_ranking_LINK_BATTLES
	para "?"
ENDM
DEF RANKING_LINK_BATTLES_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
MACRO describe_ranking_LINK_BATTLES
	para "?"
ENDM
DEF RANKING_LINK_BATTLES_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
MACRO describe_ranking_LINK_BATTLES
	para "?"
ENDM
DEF RANKING_LINK_BATTLES_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 29: Number of times players Pokémon used Splash
DEF RANKING_SPLASH_ADDR EQUS "sTrainerRankingSplash"
DEF RANKING_SPLASH_FMT  EQUS "3, 7"
DEF RANKING_SPLASH_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_SPLASH_NAME EQUS "?"
MACRO describe_ranking_SPLASH
	db   "?"
ENDM
DEF RANKING_SPLASH_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_SPLASH_NAME EQUS "SPLASH USED"
MACRO describe_ranking_SPLASH
	para "?"
ENDM
DEF RANKING_SPLASH_UNIT EQUS " times"

; German
ELIF DEF(_LANG_D)
DEF RANKING_SPLASH_NAME EQUS "PLATSCHER-EINSATZ"
MACRO describe_ranking_SPLASH
	para "?"
ENDM
DEF RANKING_SPLASH_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_SPLASH_NAME EQUS "?"
MACRO describe_ranking_SPLASH
	para "?"
ENDM
DEF RANKING_SPLASH_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_SPLASH_NAME EQUS "?"
MACRO describe_ranking_SPLASH
	para "?"
ENDM
DEF RANKING_SPLASH_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_SPLASH_NAME EQUS "?"
MACRO describe_ranking_SPLASH
	para "?"
ENDM
DEF RANKING_SPLASH_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 30: Number of tree Pokémon encounters
; actually, it doesnt care about whether an encounter happened
; only that the player used headbutt on a tree
DEF RANKING_TREE_ENCOUNTERS_ADDR EQUS "sTrainerRankingTreeEncounters"
DEF RANKING_TREE_ENCOUNTERS_FMT  EQUS "3, 7"
DEF RANKING_TREE_ENCOUNTERS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "ずつきを　した　かいすう"
MACRO describe_ranking_TREE_ENCOUNTERS
	db   "?"
ENDM
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "HEADBUTT USED"
MACRO describe_ranking_TREE_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS " times"
REDEF RANKING_TREE_ENCOUNTERS_SPACING EQU 1

; German
ELIF DEF(_LANG_D)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "KOPFNUSS-EINSATZ"
MACRO describe_ranking_TREE_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS " Mal"
REDEF RANKING_TREE_ENCOUNTERS_SPACING EQU 3

; French
ELIF DEF(_LANG_F)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "?"
MACRO describe_ranking_TREE_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "?"
MACRO describe_ranking_TREE_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "?"
MACRO describe_ranking_TREE_ENCOUNTERS
	para "?"
ENDM
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 31: Unused 3
DEF RANKING_UNUSED_3_ADDR EQUS "sTrainerRankingUnused3"
DEF RANKING_UNUSED_3_FMT  EQUS "3, 8"
DEF RANKING_UNUSED_3_SPACING EQU 1

; Japanese
IF DEF(_LANG_J)
DEF RANKING_UNUSED_3_NAME EQUS "?"
MACRO describe_ranking_UNUSED_3
	db   "?"
ENDM
DEF RANKING_UNUSED_3_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_UNUSED_3_NAME EQUS "?"
MACRO describe_ranking_UNUSED_3
	para "?"
ENDM
DEF RANKING_UNUSED_3_UNIT EQUS "?"

; German
ELIF DEF(_LANG_D)
DEF RANKING_UNUSED_3_NAME EQUS "?"
MACRO describe_ranking_UNUSED_3
	para "?"
ENDM
DEF RANKING_UNUSED_3_UNIT EQUS "?"

; French
ELIF DEF(_LANG_F)
DEF RANKING_UNUSED_3_NAME EQUS "?"
MACRO describe_ranking_UNUSED_3
	para "?"
ENDM
DEF RANKING_UNUSED_3_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_UNUSED_3_NAME EQUS "?"
MACRO describe_ranking_UNUSED_3
	para "?"
ENDM
DEF RANKING_UNUSED_3_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_UNUSED_3_NAME EQUS "?"
MACRO describe_ranking_UNUSED_3
	para "?"
ENDM
DEF RANKING_UNUSED_3_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 32: Number of Colosseum wins
DEF RANKING_LINK_WINS_ADDR EQUS "sTrainerRankingColosseumWins"
DEF RANKING_LINK_WINS_FMT  EQUS "3, 7"
DEF RANKING_LINK_WINS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_LINK_WINS_NAME EQUS "コロシアムで　かった　かいすう"
MACRO describe_ranking_LINK_WINS
	db   "?"
ENDM
DEF RANKING_LINK_WINS_UNIT EQUS "かい"

; English
ELIF DEF(_LANG_E)
DEF RANKING_LINK_WINS_NAME EQUS "COLOSSEUM WINS"
MACRO describe_ranking_LINK_WINS
	para "?"
ENDM
DEF RANKING_LINK_WINS_UNIT EQUS " wins"

; German
ELIF DEF(_LANG_D)
DEF RANKING_LINK_WINS_NAME EQUS "KOLOSSEUM-SIEGE"
MACRO describe_ranking_LINK_WINS
	para "?"
ENDM
DEF RANKING_LINK_WINS_UNIT EQUS " Siege"

; French
ELIF DEF(_LANG_F)
DEF RANKING_LINK_WINS_NAME EQUS "?"
MACRO describe_ranking_LINK_WINS
	para "?"
ENDM
DEF RANKING_LINK_WINS_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_LINK_WINS_NAME EQUS "?"
MACRO describe_ranking_LINK_WINS
	para "?"
ENDM
DEF RANKING_LINK_WINS_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_LINK_WINS_NAME EQUS "?"
MACRO describe_ranking_LINK_WINS
	para "?"
ENDM
DEF RANKING_LINK_WINS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 33: Number of Colosseum losses
DEF RANKING_LINK_LOSSES_ADDR EQUS "sTrainerRankingColosseumLosses"
DEF RANKING_LINK_LOSSES_FMT  EQUS "3, 7"
DEF RANKING_LINK_LOSSES_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
MACRO describe_ranking_LINK_LOSSES
	db   "?"
ENDM
DEF RANKING_LINK_LOSSES_UNIT EQUS "かい" ; a guess

; English
ELIF DEF(_LANG_E)
DEF RANKING_LINK_LOSSES_NAME EQUS "COLOSSEUM LOSSES"
MACRO describe_ranking_LINK_LOSSES
	para "?"
ENDM
DEF RANKING_LINK_LOSSES_UNIT EQUS " losses"
REDEF RANKING_LINK_LOSSES_SPACING EQU 0

; German
ELIF DEF(_LANG_D)
DEF RANKING_LINK_LOSSES_NAME EQUS "KOLOSSEUM-NIEDERL."
MACRO describe_ranking_LINK_LOSSES
	para "?"
ENDM
DEF RANKING_LINK_LOSSES_UNIT EQUS " Niederlagen"
REDEF RANKING_LINK_LOSSES_SPACING EQU -5

; French
ELIF DEF(_LANG_F)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
MACRO describe_ranking_LINK_LOSSES
	para "?"
ENDM
DEF RANKING_LINK_LOSSES_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
MACRO describe_ranking_LINK_LOSSES
	para "?"
ENDM
DEF RANKING_LINK_LOSSES_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
MACRO describe_ranking_LINK_LOSSES
	para "?"
ENDM
DEF RANKING_LINK_LOSSES_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 34: Number of Colosseum ties
DEF RANKING_LINK_DRAWS_ADDR EQUS "sTrainerRankingColosseumDraws"
DEF RANKING_LINK_DRAWS_FMT  EQUS "3, 7"
DEF RANKING_LINK_DRAWS_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
MACRO describe_ranking_LINK_DRAWS
	db   "?"
ENDM
DEF RANKING_LINK_DRAWS_UNIT EQUS "かい" ; a guess

; English
ELIF DEF(_LANG_E)
DEF RANKING_LINK_DRAWS_NAME EQUS "COLOSSEUM DRAWS"
MACRO describe_ranking_LINK_DRAWS
	para "?"
ENDM
DEF RANKING_LINK_DRAWS_UNIT EQUS " draws"

; German
ELIF DEF(_LANG_D)
DEF RANKING_LINK_DRAWS_NAME EQUS "KOLOSSEUM-REMIS"
MACRO describe_ranking_LINK_DRAWS
	para "?"
ENDM
DEF RANKING_LINK_DRAWS_UNIT EQUS " Remis"

; French
ELIF DEF(_LANG_F)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
MACRO describe_ranking_LINK_DRAWS
	para "?"
ENDM
DEF RANKING_LINK_DRAWS_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
MACRO describe_ranking_LINK_DRAWS
	para "?"
ENDM
DEF RANKING_LINK_DRAWS_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
MACRO describe_ranking_LINK_DRAWS
	para "?"
ENDM
DEF RANKING_LINK_DRAWS_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 35: Number of times players Pokémon used SelfDestruct or Explosion
DEF RANKING_SELFDESTRUCT_ADDR EQUS "sTrainerRankingSelfdestruct"
DEF RANKING_SELFDESTRUCT_FMT  EQUS "3, 7"
DEF RANKING_SELFDESTRUCT_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
MACRO describe_ranking_SELFDESTRUCT
	db   "?"
ENDM
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_SELFDESTRUCT_NAME EQUS "SELF-KO MOVE USED"
MACRO describe_ranking_SELFDESTRUCT
	para "?"
ENDM
DEF RANKING_SELFDESTRUCT_UNIT EQUS " times"

; German
ELIF DEF(_LANG_D)
DEF RANKING_SELFDESTRUCT_NAME EQUS "EIGEN-K.O.-EINSATZ"
MACRO describe_ranking_SELFDESTRUCT
	para "?"
ENDM
DEF RANKING_SELFDESTRUCT_UNIT EQUS " Mal"

; French
ELIF DEF(_LANG_F)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
MACRO describe_ranking_SELFDESTRUCT
	para "?"
ENDM
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
MACRO describe_ranking_SELFDESTRUCT
	para "?"
ENDM
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
MACRO describe_ranking_SELFDESTRUCT
	para "?"
ENDM
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 36: Current streak of consecutive slot machine wins
DEF RANKING_CURRENT_SLOTS_STREAK_ADDR EQUS "sTrainerRankingCurrentSlotsStreak"
DEF RANKING_CURRENT_SLOTS_STREAK_FMT  EQUS "2, 5"
DEF RANKING_CURRENT_SLOTS_STREAK_SPACING EQU 2

; Japanese
IF DEF(_LANG_J)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_CURRENT_SLOTS_STREAK
	db   "?"
ENDM
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "SLOT WIN STREAK"
MACRO describe_ranking_CURRENT_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS " wins"

; German
ELIF DEF(_LANG_D)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "SPIELH.GEWINNSERIE"
MACRO describe_ranking_CURRENT_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS " Gewinne"

; French
ELIF DEF(_LANG_F)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_CURRENT_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_CURRENT_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_CURRENT_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 37: Longest streak of consecutive slot machine wins
DEF RANKING_LONGEST_SLOTS_STREAK_ADDR EQUS "sTrainerRankingLongestSlotsStreak"
DEF RANKING_LONGEST_SLOTS_STREAK_FMT  EQUS "2, 5"
DEF RANKING_LONGEST_SLOTS_STREAK_SPACING EQU 2

; Japanese
IF DEF(_LANG_J)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_LONGEST_SLOTS_STREAK
	db   "?"
ENDM
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "BEST SLOT STREAK"
MACRO describe_ranking_LONGEST_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS " wins"

; German
ELIF DEF(_LANG_D)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "SPIELH.-REKORD"
MACRO describe_ranking_LONGEST_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS " Gewinne"

; French
ELIF DEF(_LANG_F)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_LONGEST_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_LONGEST_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
MACRO describe_ranking_LONGEST_SLOTS_STREAK
	para "?"
ENDM
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 38: Total coins won from slot machines
DEF RANKING_COINS_EARNED_ADDR EQUS "sTrainerRankingTotalSlotsPayouts"
DEF RANKING_COINS_EARNED_FMT  EQUS "4, 9"
DEF RANKING_COINS_EARNED_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
MACRO describe_ranking_COINS_EARNED
	db   "?"
ENDM
DEF RANKING_COINS_EARNED_UNIT EQUS "?"

; English
ELIF DEF(_LANG_E)
DEF RANKING_COINS_EARNED_NAME EQUS "SLOT COINS WON"
MACRO describe_ranking_COINS_EARNED
	para "?"
ENDM
DEF RANKING_COINS_EARNED_UNIT EQUS " coins"
REDEF RANKING_COINS_EARNED_SPACING EQU -1

; German
ELIF DEF(_LANG_D)
DEF RANKING_COINS_EARNED_NAME EQUS "MÜNZEN GEWONNEN"
MACRO describe_ranking_COINS_EARNED
	para "?"
ENDM
DEF RANKING_COINS_EARNED_UNIT EQUS " Münzen"

; French
ELIF DEF(_LANG_F)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
MACRO describe_ranking_COINS_EARNED
	para "?"
ENDM
DEF RANKING_COINS_EARNED_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
MACRO describe_ranking_COINS_EARNED
	para "?"
ENDM
DEF RANKING_COINS_EARNED_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
MACRO describe_ranking_COINS_EARNED
	para "?"
ENDM
DEF RANKING_COINS_EARNED_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 39: Total money earned from battles (including Pay Day)
DEF RANKING_MONEY_EARNED_ADDR EQUS "sTrainerRankingTotalBattlePayouts"
DEF RANKING_MONEY_EARNED_FMT  EQUS "4, 9"
DEF RANKING_MONEY_EARNED_SPACING EQU 0

; Japanese
IF DEF(_LANG_J)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
MACRO describe_ranking_MONEY_EARNED
	db   "?"
ENDM
DEF RANKING_MONEY_EARNED_UNIT EQUS ""

; English
ELIF DEF(_LANG_E)
DEF RANKING_MONEY_EARNED_NAME EQUS "TOTAL MONEY"
MACRO describe_ranking_MONEY_EARNED
	para "?"
ENDM
DEF RANKING_MONEY_EARNED_UNIT EQUS "¥"
REDEF RANKING_MONEY_EARNED_SPACING EQU 4

; German
ELIF DEF(_LANG_D)
DEF RANKING_MONEY_EARNED_NAME EQUS "PREISGELD GESAMT"
MACRO describe_ranking_MONEY_EARNED
	para "?"
ENDM
DEF RANKING_MONEY_EARNED_UNIT EQUS "¥"
REDEF RANKING_MONEY_EARNED_SPACING EQU 4

; French
ELIF DEF(_LANG_F)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
MACRO describe_ranking_MONEY_EARNED
	para "?"
ENDM
DEF RANKING_MONEY_EARNED_UNIT EQUS "?"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
MACRO describe_ranking_MONEY_EARNED
	para "?"
ENDM
DEF RANKING_MONEY_EARNED_UNIT EQUS "?"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
MACRO describe_ranking_MONEY_EARNED
	para "?"
ENDM
DEF RANKING_MONEY_EARNED_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 40: Largest Magikarp measured
DEF RANKING_LONGEST_MAGIKARP_ADDR EQUS "sTrainerRankingLongestMagikarp"
DEF RANKING_LONGEST_MAGIKARP_ADDR_LO EQUS "sTrainerRankingLongestMagikarpLow"
DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \"<DOT>\""
DEF RANKING_LONGEST_MAGIKARP_SPACING EQU 1

; Japanese
IF DEF(_LANG_J)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "つった　コイキング<NO>おおきさ"
DEF RANKING_LONGEST_MAGIKARP_FULLNAME EQUS "コイキング<NO>おおきさ"
MACRO describe_ranking_LONGEST_MAGIKARP
	db   "いかりのみずうみ<NI>いる"
	cont "つりめいじん<NI>はか<TTE>もらった"
	cont "コイキング<NO>うち　いちばん"
	cont "おおきかった　もので　きそいます"
ENDM
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS "センチ"

; English
ELIF DEF(_LANG_E)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "LARGEST MAGIKARP"
MACRO describe_ranking_LONGEST_MAGIKARP
	para "The size of the"
	line "largest MAGIKARP"
	cont "measured by the"
	cont "FISHING GURU at"
	cont "the LAKE OF RAGE."
ENDM
REDEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "1, 3, 0\nnts_end\ndb \"'\"\nnts_start\nnts_ranking_number $0015, 1, 2, 0"
DEF RANKING_LONGEST_MAGIKARP_FMT_PLAYER EQUS "1, 3, 0\nnts_end\ndb \"'\"\nnts_start\nnts_number {RANKING_LONGEST_MAGIKARP_ADDR_LO}, 1, 2, 0"
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS "”"
REDEF RANKING_LONGEST_MAGIKARP_SPACING EQU 7

; German
ELIF DEF(_LANG_D)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "GRÖSSTES KARPADOR"
MACRO describe_ranking_LONGEST_MAGIKARP
	para "Das größte"
	line "KARPADOR, das"
	cont "vom PROFI-ANGLER"
	cont "am SEE DES ZORNS"
	cont "gemessen wurde."
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS " cm"

; French
ELIF DEF(_LANG_F)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "GIGA MAGICARPE"
MACRO describe_ranking_LONGEST_MAGIKARP
	para "La taille du plus"
	line "grand MAGICARPE"
	cont "mesuré par le"
	cont "MAITRE PECHEUR"
	cont "au LAC COLERE."
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS " cm"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "MAGIKARP PIÙ GR."
DEF RANKING_LONGEST_MAGIKARP_FULLNAME EQUS "IL MAGIKARP PIÙ<LINE>GROSSO"
MACRO describe_ranking_LONGEST_MAGIKARP
	para "Le dimensioni del"
	line "MAGIKARP più"
	cont "grosso per il GURU"
	cont "PESCATORE al"
	cont "LAGO D'IRA."
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS " cm"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "?"
MACRO describe_ranking_LONGEST_MAGIKARP
	para "?"
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 41: Smallest Magikarp measured
DEF RANKING_SHORTEST_MAGIKARP_ADDR EQUS "sTrainerRankingShortestMagikarp"
DEF RANKING_SHORTEST_MAGIKARP_ADDR_LO EQUS "sTrainerRankingShortestMagikarpLow"
DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \"<DOT>\""
DEF RANKING_SHORTEST_MAGIKARP_SPACING EQU 1

; Japanese
IF DEF(_LANG_J)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
MACRO describe_ranking_SHORTEST_MAGIKARP
	db   "?"
ENDM
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS "センチ"

; English
ELIF DEF(_LANG_E)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "SMALLEST MAGIKARP"
MACRO describe_ranking_SHORTEST_MAGIKARP
	para "?"
ENDM
REDEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "1, 3\nnts_end\ndb \"'\"\nnts_start\nnts_ranking_number $0015, 1, 2"
DEF RANKING_SHORTEST_MAGIKARP_FMT_PLAYER EQUS "1, 3\nnts_end\ndb \"'\"\nnts_start\nnts_number {RANKING_SHORTEST_MAGIKARP_ADDR_LO}, 1, 2"
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS "”"
REDEF RANKING_SHORTEST_MAGIKARP_SPACING EQU 7

; German
ELIF DEF(_LANG_D)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
MACRO describe_ranking_SHORTEST_MAGIKARP
	para "?"
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS " cm"

; French
ELIF DEF(_LANG_F)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
MACRO describe_ranking_SHORTEST_MAGIKARP
	para "?"
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS " cm"

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
MACRO describe_ranking_SHORTEST_MAGIKARP
	para "?"
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS " cm"

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
MACRO describe_ranking_SHORTEST_MAGIKARP
	para "?"
ENDM
; uncomment to print with a ',' as the decimal separator
;REDEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS "?"
ENDC


; --------------------------------
; Ranking 42: Bug-Catching Contest high score
DEF RANKING_BUG_CONTEST_SCORE_ADDR EQUS "sTrainerRankingBugContestScore"
DEF RANKING_BUG_CONTEST_SCORE_FMT  EQUS "2, 5"
DEF RANKING_BUG_CONTEST_SCORE_SPACING EQU 1

; Japanese
IF DEF(_LANG_J)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "むしとりたいかい　こうとくてん"
MACRO describe_ranking_BUG_CONTEST_SCORE
	db   "しぜんこうえんで　おこなわれる"
	cont "むしとりたいかいで　これまでに"
	cont "とった　いちばん　たかい"
	cont "てんすうで　きそいます"
ENDM
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS "てん"

; English
ELIF DEF(_LANG_E)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "BUG CONTEST SCORE"
MACRO describe_ranking_BUG_CONTEST_SCORE
	para "The highest score"
	line "obtained at the"
	cont "BUG-CATCHING Con-"
	cont "test held in the"
	cont "NATIONAL PARK."
ENDM
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " points"
REDEF RANKING_BUG_CONTEST_SCORE_SPACING EQU 2
; Rework in other languages

; German
ELIF DEF(_LANG_D)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "KÄFER-TURNIER"
MACRO describe_ranking_BUG_CONTEST_SCORE
	para "Die höchste Punkt-"
	line "zahl beim KÄFER-"
	cont "TURNIER im"
	cont "NATIONALPARK."
ENDM
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " Punkte"
REDEF RANKING_BUG_CONTEST_SCORE_SPACING EQU 2

; French
ELIF DEF(_LANG_F)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "CAPTURE D'INSECTE"
MACRO describe_ranking_BUG_CONTEST_SCORE
	para "Le plus haut score"
	line "obtenu au Concours"
	cont "de Capture d'inse-"
	cont "cte qui se déroule"
	cont "au PARC NATUREL."
ENDM
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " points"
REDEF RANKING_BUG_CONTEST_SCORE_SPACING EQU 2

; Italian
ELIF DEF(_LANG_I)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "GARA PIGLIAMOSCHE"
MACRO describe_ranking_BUG_CONTEST_SCORE
	para "Il punteggio più"
	line "alto ottenuto alla"
	cont "GARA PIGLIAMOSCHE"
	cont "tenuta nel PARCO"
	cont "NAZIONALE."
ENDM
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " punti"
REDEF RANKING_BUG_CONTEST_SCORE_SPACING EQU 3

; Spanish
ELIF DEF(_LANG_S)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "?"
MACRO describe_ranking_BUG_CONTEST_SCORE
	para "?"
ENDM
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS "?"
ENDC