; Ranking 1: Play time when last entered the Hall of Fame
DEF RANKING_GAME_TIME_HOF_ADDR EQUS "sTrainerRankingGameTimeHOFHours"
DEF RANKING_GAME_TIME_HOF_ADDR_MIN EQUS "sTrainerRankingGameTimeHOFMinutes"
DEF RANKING_GAME_TIME_HOF_ADDR_SEC EQUS "sTrainerRankingGameTimeHOFSeconds"
DEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $0016, PRINTNUM_LEADINGZEROS | 1, 2\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $0017, PRINTNUM_LEADINGZEROS | 1, 2"
;DEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $0016, PRINTNUM_LEADINGZEROS | 1, 2"
DEF RANKING_GAME_TIME_HOF_FMT_PLAYER EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_number {RANKING_GAME_TIME_HOF_ADDR_MIN}, PRINTNUM_LEADINGZEROS | 1, 2\nnts_end\ndb $6D\nnts_start\nnts_number {RANKING_GAME_TIME_HOF_ADDR_SEC}, PRINTNUM_LEADINGZEROS | 1, 2"
DEF RANKING_GAME_TIME_HOF_SPACING EQU 0

IF DEF(_LANG_J)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
REDEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $001A, PRINTNUM_LEADINGZEROS | 1, 2\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $001A, PRINTNUM_LEADINGZEROS | 1, 2"
;REDEF RANKING_GAME_TIME_HOF_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 3\nnts_end\ndb $6D\nnts_start\nnts_ranking_number $001A, PRINTNUM_LEADINGZEROS | 1, 2"
DEF RANKING_GAME_TIME_HOF_DESC EQUS "?"
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""
ELIF DEF(_LANG_E)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
DEF RANKING_GAME_TIME_HOF_DESC EQUS "<PARA>?"
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""
ELIF DEF(_LANG_D)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
DEF RANKING_GAME_TIME_HOF_DESC EQUS "<PARA>?"
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""
ELIF DEF(_LANG_F)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
DEF RANKING_GAME_TIME_HOF_DESC EQUS "<PARA>?"
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""
ELIF DEF(_LANG_I)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
DEF RANKING_GAME_TIME_HOF_DESC EQUS "<PARA>?"
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""
ELIF DEF(_LANG_S)
DEF RANKING_GAME_TIME_HOF_NAME EQUS "?"
DEF RANKING_GAME_TIME_HOF_DESC EQUS "<PARA>?"
DEF RANKING_GAME_TIME_HOF_UNIT EQUS ""
ENDC

; Ranking 2: Step count when last entered the Hall of Fame
DEF RANKING_STEP_COUNT_HOF_ADDR EQUS "sTrainerRankingStepCountHOF"
DEF RANKING_STEP_COUNT_HOF_FMT  EQUS "4, 9"
DEF RANKING_STEP_COUNT_HOF_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
DEF RANKING_STEP_COUNT_HOF_DESC EQUS "?"
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS ""
ELIF DEF(_LANG_E)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
DEF RANKING_STEP_COUNT_HOF_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS " steps"
REDEF RANKING_STEP_COUNT_HOF_SPACING EQU -1
ELIF DEF(_LANG_D)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
DEF RANKING_STEP_COUNT_HOF_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
DEF RANKING_STEP_COUNT_HOF_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
DEF RANKING_STEP_COUNT_HOF_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_STEP_COUNT_HOF_NAME EQUS "?"
DEF RANKING_STEP_COUNT_HOF_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_HOF_UNIT EQUS "?"
ENDC

; Ranking 3: Number of times the party was healed when last entered the Hall of Fame
DEF RANKING_HEALINGS_HOF_ADDR EQUS "sTrainerRankingHealingsHOF"
DEF RANKING_HEALINGS_HOF_FMT  EQUS "4, 9"
DEF RANKING_HEALINGS_HOF_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
DEF RANKING_HEALINGS_HOF_DESC EQUS "?"
DEF RANKING_HEALINGS_HOF_UNIT EQUS ""
ELIF DEF(_LANG_E)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
DEF RANKING_HEALINGS_HOF_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_D)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
DEF RANKING_HEALINGS_HOF_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
DEF RANKING_HEALINGS_HOF_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
DEF RANKING_HEALINGS_HOF_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_HEALINGS_HOF_NAME EQUS "?"
DEF RANKING_HEALINGS_HOF_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_HOF_UNIT EQUS "?"
ENDC

; Ranking 4: Number of battles when last entered the Hall of Fame
; Copies from Ranking 8 during hall of fame sequence
; INCLUDES:
; - wild battles
; - trainer battles
; - bug contest battles
; - link battles
; - other battle types im forgetting
; EXCLUDES:
; - catching tutorial
DEF RANKING_BATTLES_HOF_ADDR EQUS "sTrainerRankingBattlesHOF"
DEF RANKING_BATTLES_HOF_FMT  EQUS "3, 7"
DEF RANKING_BATTLES_HOF_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
DEF RANKING_BATTLES_HOF_DESC EQUS "?"
DEF RANKING_BATTLES_HOF_UNIT EQUS "かい" ; a guess
ELIF DEF(_LANG_E)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
DEF RANKING_BATTLES_HOF_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_D)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
DEF RANKING_BATTLES_HOF_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
DEF RANKING_BATTLES_HOF_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
DEF RANKING_BATTLES_HOF_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_BATTLES_HOF_NAME EQUS "?"
DEF RANKING_BATTLES_HOF_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_HOF_UNIT EQUS "?"
ENDC

; Ranking 5: Step count
DEF RANKING_STEP_COUNT_ADDR EQUS "sTrainerRankingStepCount"
DEF RANKING_STEP_COUNT_FMT  EQUS "4, 9"
DEF RANKING_STEP_COUNT_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
DEF RANKING_STEP_COUNT_DESC EQUS "?"
DEF RANKING_STEP_COUNT_UNIT EQUS ""
ELIF DEF(_LANG_E)
DEF RANKING_STEP_COUNT_NAME EQUS "STEPS TAKEN"
DEF RANKING_STEP_COUNT_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_UNIT EQUS " steps"
REDEF RANKING_STEP_COUNT_SPACING EQU -1
ELIF DEF(_LANG_D)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
DEF RANKING_STEP_COUNT_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
DEF RANKING_STEP_COUNT_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
DEF RANKING_STEP_COUNT_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_STEP_COUNT_NAME EQUS "?"
DEF RANKING_STEP_COUNT_DESC EQUS "<PARA>?"
DEF RANKING_STEP_COUNT_UNIT EQUS "?"
ENDC

; Ranking 6: Number of Battle Tower Wins
DEF RANKING_BATTLE_TOWER_WINS_ADDR EQUS "sTrainerRankingBattleTowerWins"
; 2, 5, SPACING=1 matches. 4, (6 or 7) works
;DEF RANKING_BATTLE_TOWER_WINS_FMT  EQUS "2, 5"
DEF RANKING_BATTLE_TOWER_WINS_FMT  EQUS "4, 7"
DEF RANKING_BATTLE_TOWER_WINS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "バトルタワーで　かった　かいすう"
DEF RANKING_BATTLE_TOWER_WINS_DESC EQUS "４０ばんどうろ<NO>バトルタワーで<CONT>あなた<GA>これまで<NI>なんにんの<CONT><TRAINER>と<NO>しょうぶ<NI>かったか<CONT>にんずうで　きそいます"
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "BATTLE TOWER WINS"
DEF RANKING_BATTLE_TOWER_WINS_DESC EQUS "<PARA>The number of<LINE>#MON battles<CONT>won against other<CONT><TRAINER>S at the<CONT>BATTLE TOWER on<CONT>ROUTE 40."
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " wins"
ELIF DEF(_LANG_D)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "DUELLTURM"
DEF RANKING_BATTLE_TOWER_WINS_DESC EQUS "<PARA>Die Anzahl der<LINE>gewonnenen<CONT>#MON-Kämpfe<CONT>gegen andere<CONT><TRAINER> beim<CONT>DUELLTURM auf<CONT>ROUTE 40."
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " Punkte"
ELIF DEF(_LANG_F)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "TOUR DE COMBAT"
DEF RANKING_BATTLE_TOWER_WINS_DESC EQUS "<PARA>Nombre de<LINE>combats #MON<CONT>gagnés contre les<CONT><TRAINER>S dans<CONT>la TOUR de COMBAT<CONT>sur la ROUTE 40."
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " points"
ELIF DEF(_LANG_I)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "TORRE LOTTA"
DEF RANKING_BATTLE_TOWER_WINS_DESC EQUS "<PARA>Il numero di lotte<LINE>#MON vinte<CONT>contro gli<CONT>ALLENATORI alla<CONT>TORRE LOTTA sul<CONT>PERCORSO 40."
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS " punti"
ELIF DEF(_LANG_S)
DEF RANKING_BATTLE_TOWER_WINS_NAME EQUS "?"
DEF RANKING_BATTLE_TOWER_WINS_DESC EQUS "<PARA>?"
DEF RANKING_BATTLE_TOWER_WINS_UNIT EQUS "?"
ENDC

; Ranking 7: Number of times TMs and HMs have been taught
DEF RANKING_TMS_HMS_TAUGHT_ADDR EQUS "sTrainerRankingTMsHMsTaught"
DEF RANKING_TMS_HMS_TAUGHT_FMT  EQUS "3, 7"
DEF RANKING_TMS_HMS_TAUGHT_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
DEF RANKING_TMS_HMS_TAUGHT_DESC EQUS "?"
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "TMs/HMs TAUGHT"
DEF RANKING_TMS_HMS_TAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS " taught"
ELIF DEF(_LANG_D)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
DEF RANKING_TMS_HMS_TAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
DEF RANKING_TMS_HMS_TAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
DEF RANKING_TMS_HMS_TAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_TMS_HMS_TAUGHT_NAME EQUS "?"
DEF RANKING_TMS_HMS_TAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_TMS_HMS_TAUGHT_UNIT EQUS "?"
ENDC

; Ranking 8: Number of battles
; incremented during `BattleIntro`
; INCLUDES:
; - wild battles
; - trainer battles
; - bug contest battles
; - link battles
; - other battle types im forgetting
; SPECIFICALLY EXCLUDES:
; - catching tutorial
DEF RANKING_BATTLES_ADDR EQUS "sTrainerRankingBattles"
DEF RANKING_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_BATTLES_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_BATTLES_NAME EQUS "ポケモンと　たたかった　かいすう"
DEF RANKING_BATTLES_DESC EQUS "?"
DEF RANKING_BATTLES_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_BATTLES_NAME EQUS "#MON BATTLES"
DEF RANKING_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_UNIT EQUS " battles"
ELIF DEF(_LANG_D)
DEF RANKING_BATTLES_NAME EQUS "?"
DEF RANKING_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_BATTLES_NAME EQUS "?"
DEF RANKING_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_BATTLES_NAME EQUS "?"
DEF RANKING_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_BATTLES_NAME EQUS "?"
DEF RANKING_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_BATTLES_UNIT EQUS "?"
ENDC

; Ranking 9: Number of wild Pokémon battles
; incremented during `InitEnemyWildmon`
; INCLUDES
; - wild battles
; - bug contest battles
; EXCLUDES:
; - catching tutorial
; - trainer battles
; - link battles
DEF RANKING_WILD_BATTLES_ADDR EQUS "sTrainerRankingWildBattles"
DEF RANKING_WILD_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_WILD_BATTLES_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
DEF RANKING_WILD_BATTLES_DESC EQUS "?"
DEF RANKING_WILD_BATTLES_UNIT EQUS "かい" ; a guess
ELIF DEF(_LANG_E)
DEF RANKING_WILD_BATTLES_NAME EQUS "WILD <PKMN> BATTLES"
DEF RANKING_WILD_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_WILD_BATTLES_UNIT EQUS " battles"
ELIF DEF(_LANG_D)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
DEF RANKING_WILD_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_WILD_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
DEF RANKING_WILD_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_WILD_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
DEF RANKING_WILD_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_WILD_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_WILD_BATTLES_NAME EQUS "?"
DEF RANKING_WILD_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_WILD_BATTLES_UNIT EQUS "?"
ENDC

; Ranking 10: Number of Trainer battles
; incremented during `InitEnemyTrainer`
; INCLUDES
; - trainer battles
; - link battles
; EXCLUDES:
; - catching tutorial
; - wild battles
; - bug contest battles
DEF RANKING_TRAINER_BATTLES_ADDR EQUS "sTrainerRankingTrainerBattles"
DEF RANKING_TRAINER_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_TRAINER_BATTLES_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
DEF RANKING_TRAINER_BATTLES_DESC EQUS "?"
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "かい" ; a guess
ELIF DEF(_LANG_E)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "TRAINER BATTLES"
DEF RANKING_TRAINER_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_TRAINER_BATTLES_UNIT EQUS " battles"
ELIF DEF(_LANG_D)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
DEF RANKING_TRAINER_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
DEF RANKING_TRAINER_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
DEF RANKING_TRAINER_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_TRAINER_BATTLES_NAME EQUS "?"
DEF RANKING_TRAINER_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_TRAINER_BATTLES_UNIT EQUS "?"
ENDC

; Ranking 11: Unused 1
DEF RANKING_UNUSED_1_ADDR EQUS "sTrainerRankingUnused1"
DEF RANKING_UNUSED_1_FMT  EQUS "3, 8"
DEF RANKING_UNUSED_1_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_UNUSED_1_NAME EQUS "?"
DEF RANKING_UNUSED_1_DESC EQUS "?"
DEF RANKING_UNUSED_1_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_UNUSED_1_NAME EQUS "?"
DEF RANKING_UNUSED_1_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_1_UNIT EQUS "?"
ELIF DEF(_LANG_D)
DEF RANKING_UNUSED_1_NAME EQUS "?"
DEF RANKING_UNUSED_1_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_1_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_UNUSED_1_NAME EQUS "?"
DEF RANKING_UNUSED_1_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_1_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_UNUSED_1_NAME EQUS "?"
DEF RANKING_UNUSED_1_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_1_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_UNUSED_1_NAME EQUS "?"
DEF RANKING_UNUSED_1_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_1_UNIT EQUS "?"
ENDC

; Ranking 12: Number of Hall of Fame inductions
DEF RANKING_HOF_ENTRIES_ADDR EQUS "sTrainerRankingHOFEntries"
DEF RANKING_HOF_ENTRIES_FMT  EQUS "3, 7"
DEF RANKING_HOF_ENTRIES_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
DEF RANKING_HOF_ENTRIES_DESC EQUS "?"
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_HOF_ENTRIES_NAME EQUS "HALL OF FAME COUNT"
DEF RANKING_HOF_ENTRIES_DESC EQUS "<PARA>?"
DEF RANKING_HOF_ENTRIES_UNIT EQUS " entries"
ELIF DEF(_LANG_D)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
DEF RANKING_HOF_ENTRIES_DESC EQUS "<PARA>?"
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
DEF RANKING_HOF_ENTRIES_DESC EQUS "<PARA>?"
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
DEF RANKING_HOF_ENTRIES_DESC EQUS "<PARA>?"
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_HOF_ENTRIES_NAME EQUS "?"
DEF RANKING_HOF_ENTRIES_DESC EQUS "<PARA>?"
DEF RANKING_HOF_ENTRIES_UNIT EQUS "?"
ENDC

; Ranking 13: Number of wild Pokémon caught
DEF RANKING_WILD_MONS_CAUGHT_ADDR EQUS "sTrainerRankingWildMonsCaught"
DEF RANKING_WILD_MONS_CAUGHT_FMT  EQUS "3, 7"
DEF RANKING_WILD_MONS_CAUGHT_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "つかまえた　ポケモンの　かず"
DEF RANKING_WILD_MONS_CAUGHT_DESC EQUS "?"
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "ひき"
ELIF DEF(_LANG_E)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "#MON CAUGHT"
DEF RANKING_WILD_MONS_CAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS " caught"
ELIF DEF(_LANG_D)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "?"
DEF RANKING_WILD_MONS_CAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "?"
DEF RANKING_WILD_MONS_CAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "?"
DEF RANKING_WILD_MONS_CAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_WILD_MONS_CAUGHT_NAME EQUS "?"
DEF RANKING_WILD_MONS_CAUGHT_DESC EQUS "<PARA>?"
DEF RANKING_WILD_MONS_CAUGHT_UNIT EQUS "?"
ENDC

; Ranking 14: Number of hooked Pokémon encounters
DEF RANKING_HOOKED_ENCOUNTERS_ADDR EQUS "sTrainerRankingHookedEncounters"
DEF RANKING_HOOKED_ENCOUNTERS_FMT  EQUS "3, 7"
DEF RANKING_HOOKED_ENCOUNTERS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "ポケモンを　つった　かいすう"
DEF RANKING_HOOKED_ENCOUNTERS_DESC EQUS "?"
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "#MON HOOKED"
DEF RANKING_HOOKED_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS " hooked"
ELIF DEF(_LANG_D)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_HOOKED_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_HOOKED_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_HOOKED_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_HOOKED_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_HOOKED_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_HOOKED_ENCOUNTERS_UNIT EQUS "?"
ENDC

; Ranking 15: Number of Eggs hatched
DEF RANKING_EGGS_HATCHED_ADDR EQUS "sTrainerRankingEggsHatched"
DEF RANKING_EGGS_HATCHED_FMT  EQUS "3, 7"
DEF RANKING_EGGS_HATCHED_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_EGGS_HATCHED_NAME EQUS "タマゴを　かえした　かいすう"
DEF RANKING_EGGS_HATCHED_DESC EQUS "?"
DEF RANKING_EGGS_HATCHED_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_EGGS_HATCHED_NAME EQUS "EGGS HATCHED"
DEF RANKING_EGGS_HATCHED_DESC EQUS "<PARA>?"
DEF RANKING_EGGS_HATCHED_UNIT EQUS " EGGs"
ELIF DEF(_LANG_D)
DEF RANKING_EGGS_HATCHED_NAME EQUS "?"
DEF RANKING_EGGS_HATCHED_DESC EQUS "<PARA>?"
DEF RANKING_EGGS_HATCHED_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_EGGS_HATCHED_NAME EQUS "?"
DEF RANKING_EGGS_HATCHED_DESC EQUS "<PARA>?"
DEF RANKING_EGGS_HATCHED_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_EGGS_HATCHED_NAME EQUS "?"
DEF RANKING_EGGS_HATCHED_DESC EQUS "<PARA>?"
DEF RANKING_EGGS_HATCHED_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_EGGS_HATCHED_NAME EQUS "?"
DEF RANKING_EGGS_HATCHED_DESC EQUS "<PARA>?"
DEF RANKING_EGGS_HATCHED_UNIT EQUS "?"
ENDC

; Ranking 16: Number of Pokémon evolved
DEF RANKING_MONS_EVOLVED_ADDR EQUS "sTrainerRankingMonsEvolved"
DEF RANKING_MONS_EVOLVED_FMT  EQUS "3, 7"
DEF RANKING_MONS_EVOLVED_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_MONS_EVOLVED_NAME EQUS "ポケモンが　しんかした　かいすう"
DEF RANKING_MONS_EVOLVED_DESC EQUS "?"
DEF RANKING_MONS_EVOLVED_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_MONS_EVOLVED_NAME EQUS "#MON EVOLVED"
DEF RANKING_MONS_EVOLVED_DESC EQUS "<PARA>?"
DEF RANKING_MONS_EVOLVED_UNIT EQUS " evolved"
ELIF DEF(_LANG_D)
DEF RANKING_MONS_EVOLVED_NAME EQUS "?"
DEF RANKING_MONS_EVOLVED_DESC EQUS "<PARA>?"
DEF RANKING_MONS_EVOLVED_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_MONS_EVOLVED_NAME EQUS "?"
DEF RANKING_MONS_EVOLVED_DESC EQUS "<PARA>?"
DEF RANKING_MONS_EVOLVED_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_MONS_EVOLVED_NAME EQUS "?"
DEF RANKING_MONS_EVOLVED_DESC EQUS "<PARA>?"
DEF RANKING_MONS_EVOLVED_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_MONS_EVOLVED_NAME EQUS "?"
DEF RANKING_MONS_EVOLVED_DESC EQUS "<PARA>?"
DEF RANKING_MONS_EVOLVED_UNIT EQUS "?"
ENDC

; Ranking 17: Number of Berries and Apricorns picked
; includes any item obtained from a "fruit tree" object
DEF RANKING_FRUIT_PICKED_ADDR EQUS "sTrainerRankingFruitPicked"
DEF RANKING_FRUIT_PICKED_FMT  EQUS "3, 7"
DEF RANKING_FRUIT_PICKED_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_FRUIT_PICKED_NAME EQUS "とった　きのみの　かず"
DEF RANKING_FRUIT_PICKED_DESC EQUS "?"
DEF RANKING_FRUIT_PICKED_UNIT EQUS "こ"
ELIF DEF(_LANG_E)
; name "FRUIT" was chosen because of the first line
; when interacting with the berry/apricorn tree object:
; "It's a fruit-bearing tree."
DEF RANKING_FRUIT_PICKED_NAME EQUS "FRUIT PICKED"
DEF RANKING_FRUIT_PICKED_DESC EQUS "<PARA>?"
DEF RANKING_FRUIT_PICKED_UNIT EQUS " fruit"
ELIF DEF(_LANG_D)
DEF RANKING_FRUIT_PICKED_NAME EQUS "?"
DEF RANKING_FRUIT_PICKED_DESC EQUS "<PARA>?"
DEF RANKING_FRUIT_PICKED_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_FRUIT_PICKED_NAME EQUS "?"
DEF RANKING_FRUIT_PICKED_DESC EQUS "<PARA>?"
DEF RANKING_FRUIT_PICKED_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_FRUIT_PICKED_NAME EQUS "?"
DEF RANKING_FRUIT_PICKED_DESC EQUS "<PARA>?"
DEF RANKING_FRUIT_PICKED_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_FRUIT_PICKED_NAME EQUS "?"
DEF RANKING_FRUIT_PICKED_DESC EQUS "<PARA>?"
DEF RANKING_FRUIT_PICKED_UNIT EQUS "?"
ENDC

; Ranking 18: Number of times the party is healed
; INCLUDES
; - the healing machine in elm's lab
; - sleeping in your cabin in the fast ship
; - being healed before a mobile battle
; - the scene with mr. pokémon and oak at the start of the game
; - the healer on rt. 26
; - lance healing the party in rocket base b2f
; - pokémon center nurse
; - pokécom center nurse
DEF RANKING_HEALINGS_ADDR EQUS "sTrainerRankingHealings"
DEF RANKING_HEALINGS_FMT  EQUS "3, 7"
DEF RANKING_HEALINGS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_HEALINGS_NAME EQUS "?"
DEF RANKING_HEALINGS_DESC EQUS "?"
DEF RANKING_HEALINGS_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_HEALINGS_NAME EQUS "FULLY HEALED COUNT"
DEF RANKING_HEALINGS_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_UNIT EQUS " heals"
ELIF DEF(_LANG_D)
DEF RANKING_HEALINGS_NAME EQUS "?"
DEF RANKING_HEALINGS_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_HEALINGS_NAME EQUS "?"
DEF RANKING_HEALINGS_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_HEALINGS_NAME EQUS "?"
DEF RANKING_HEALINGS_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_HEALINGS_NAME EQUS "?"
DEF RANKING_HEALINGS_DESC EQUS "<PARA>?"
DEF RANKING_HEALINGS_UNIT EQUS "?"
ENDC

; Ranking 19: Number of times Mystery Gift is used
DEF RANKING_MYSTERY_GIFT_ADDR EQUS "sTrainerRankingMysteryGift"
DEF RANKING_MYSTERY_GIFT_FMT  EQUS "3, 7"
DEF RANKING_MYSTERY_GIFT_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "ふしぎな　おくりものの　かいすう"
DEF RANKING_MYSTERY_GIFT_DESC EQUS "?"
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "USED MYSTERY GIFT"
DEF RANKING_MYSTERY_GIFT_DESC EQUS "<PARA>?"
DEF RANKING_MYSTERY_GIFT_UNIT EQUS " gifts"
ELIF DEF(_LANG_D)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "?"
DEF RANKING_MYSTERY_GIFT_DESC EQUS "<PARA>?"
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "?"
DEF RANKING_MYSTERY_GIFT_DESC EQUS "<PARA>?"
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "?"
DEF RANKING_MYSTERY_GIFT_DESC EQUS "<PARA>?"
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_MYSTERY_GIFT_NAME EQUS "?"
DEF RANKING_MYSTERY_GIFT_DESC EQUS "<PARA>?"
DEF RANKING_MYSTERY_GIFT_UNIT EQUS "?"
ENDC

; Ranking 20: Number of trades
DEF RANKING_TRADES_ADDR EQUS "sTrainerRankingTrades"
DEF RANKING_TRADES_FMT  EQUS "3, 7"
DEF RANKING_TRADES_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_TRADES_NAME EQUS "?"
DEF RANKING_TRADES_DESC EQUS "?"
DEF RANKING_TRADES_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_TRADES_NAME EQUS "TRADES COMPLETED"
DEF RANKING_TRADES_DESC EQUS "<PARA>?"
DEF RANKING_TRADES_UNIT EQUS " trades"
ELIF DEF(_LANG_D)
DEF RANKING_TRADES_NAME EQUS "?"
DEF RANKING_TRADES_DESC EQUS "<PARA>?"
DEF RANKING_TRADES_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_TRADES_NAME EQUS "?"
DEF RANKING_TRADES_DESC EQUS "<PARA>?"
DEF RANKING_TRADES_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_TRADES_NAME EQUS "?"
DEF RANKING_TRADES_DESC EQUS "<PARA>?"
DEF RANKING_TRADES_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_TRADES_NAME EQUS "?"
DEF RANKING_TRADES_DESC EQUS "<PARA>?"
DEF RANKING_TRADES_UNIT EQUS "?"
ENDC

; Ranking 21: Number of uses of field move Fly
DEF RANKING_FLY_ADDR EQUS "sTrainerRankingFly"
DEF RANKING_FLY_FMT  EQUS "3, 7"
DEF RANKING_FLY_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_FLY_NAME EQUS "?"
DEF RANKING_FLY_DESC EQUS "?"
DEF RANKING_FLY_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_FLY_NAME EQUS "USED FLY"
DEF RANKING_FLY_DESC EQUS "<PARA>?"
DEF RANKING_FLY_UNIT EQUS " times"
ELIF DEF(_LANG_D)
DEF RANKING_FLY_NAME EQUS "?"
DEF RANKING_FLY_DESC EQUS "<PARA>?"
DEF RANKING_FLY_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_FLY_NAME EQUS "?"
DEF RANKING_FLY_DESC EQUS "<PARA>?"
DEF RANKING_FLY_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_FLY_NAME EQUS "?"
DEF RANKING_FLY_DESC EQUS "<PARA>?"
DEF RANKING_FLY_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_FLY_NAME EQUS "?"
DEF RANKING_FLY_DESC EQUS "<PARA>?"
DEF RANKING_FLY_UNIT EQUS "?"
ENDC

; Ranking 22: Number of uses of field move Surf
DEF RANKING_SURF_ADDR EQUS "sTrainerRankingSurf"
DEF RANKING_SURF_FMT  EQUS "3, 7"
DEF RANKING_SURF_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_SURF_NAME EQUS "?"
DEF RANKING_SURF_DESC EQUS "?"
DEF RANKING_SURF_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_SURF_NAME EQUS "USED SURF"
DEF RANKING_SURF_DESC EQUS "<PARA>?"
DEF RANKING_SURF_UNIT EQUS " times"
ELIF DEF(_LANG_D)
DEF RANKING_SURF_NAME EQUS "?"
DEF RANKING_SURF_DESC EQUS "<PARA>?"
DEF RANKING_SURF_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_SURF_NAME EQUS "?"
DEF RANKING_SURF_DESC EQUS "<PARA>?"
DEF RANKING_SURF_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_SURF_NAME EQUS "?"
DEF RANKING_SURF_DESC EQUS "<PARA>?"
DEF RANKING_SURF_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_SURF_NAME EQUS "?"
DEF RANKING_SURF_DESC EQUS "<PARA>?"
DEF RANKING_SURF_UNIT EQUS "?"
ENDC

; Ranking 23: Number of uses of field move Waterfall
DEF RANKING_WATERFALL_ADDR EQUS "sTrainerRankingWaterfall"
DEF RANKING_WATERFALL_FMT  EQUS "3, 7"
DEF RANKING_WATERFALL_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_WATERFALL_NAME EQUS "?"
DEF RANKING_WATERFALL_DESC EQUS "?"
DEF RANKING_WATERFALL_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_WATERFALL_NAME EQUS "USED WATERFALL"
DEF RANKING_WATERFALL_DESC EQUS "<PARA>?"
DEF RANKING_WATERFALL_UNIT EQUS " times"
ELIF DEF(_LANG_D)
DEF RANKING_WATERFALL_NAME EQUS "?"
DEF RANKING_WATERFALL_DESC EQUS "<PARA>?"
DEF RANKING_WATERFALL_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_WATERFALL_NAME EQUS "?"
DEF RANKING_WATERFALL_DESC EQUS "<PARA>?"
DEF RANKING_WATERFALL_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_WATERFALL_NAME EQUS "?"
DEF RANKING_WATERFALL_DESC EQUS "<PARA>?"
DEF RANKING_WATERFALL_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_WATERFALL_NAME EQUS "?"
DEF RANKING_WATERFALL_DESC EQUS "<PARA>?"
DEF RANKING_WATERFALL_UNIT EQUS "?"
ENDC

; Ranking 24: Number of times the player whited out
DEF RANKING_WHITE_OUTS_ADDR EQUS "sTrainerRankingWhiteOuts"
DEF RANKING_WHITE_OUTS_FMT  EQUS "3, 7"
DEF RANKING_WHITE_OUTS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
DEF RANKING_WHITE_OUTS_DESC EQUS "?"
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_WHITE_OUTS_NAME EQUS "WHITED OUT COUNT"
DEF RANKING_WHITE_OUTS_DESC EQUS "<PARA>?"
DEF RANKING_WHITE_OUTS_UNIT EQUS " times"
ELIF DEF(_LANG_D)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
DEF RANKING_WHITE_OUTS_DESC EQUS "<PARA>?"
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
DEF RANKING_WHITE_OUTS_DESC EQUS "<PARA>?"
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
DEF RANKING_WHITE_OUTS_DESC EQUS "<PARA>?"
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_WHITE_OUTS_NAME EQUS "?"
DEF RANKING_WHITE_OUTS_DESC EQUS "<PARA>?"
DEF RANKING_WHITE_OUTS_UNIT EQUS "?"
ENDC

; Ranking 25: Number of Lucky Number Show prizes won
DEF RANKING_LUCKY_NUMBER_SHOW_ADDR EQUS "sTrainerRankingLuckyNumberShow"
DEF RANKING_LUCKY_NUMBER_SHOW_FMT  EQUS "3, 7"
DEF RANKING_LUCKY_NUMBER_SHOW_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
DEF RANKING_LUCKY_NUMBER_SHOW_DESC EQUS "?"
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "LUCKY NUMBER WINS"
DEF RANKING_LUCKY_NUMBER_SHOW_DESC EQUS "<PARA>?"
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS " prizes"
ELIF DEF(_LANG_D)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
DEF RANKING_LUCKY_NUMBER_SHOW_DESC EQUS "<PARA>?"
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
DEF RANKING_LUCKY_NUMBER_SHOW_DESC EQUS "<PARA>?"
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
DEF RANKING_LUCKY_NUMBER_SHOW_DESC EQUS "<PARA>?"
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_LUCKY_NUMBER_SHOW_NAME EQUS "?"
DEF RANKING_LUCKY_NUMBER_SHOW_DESC EQUS "<PARA>?"
DEF RANKING_LUCKY_NUMBER_SHOW_UNIT EQUS "?"
ENDC

; Ranking 26: Number of Phone calls made and received
DEF RANKING_PHONE_CALLS_ADDR EQUS "sTrainerRankingPhoneCalls"
DEF RANKING_PHONE_CALLS_FMT  EQUS "3, 7"
DEF RANKING_PHONE_CALLS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
DEF RANKING_PHONE_CALLS_DESC EQUS "?"
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_PHONE_CALLS_NAME EQUS "PHONE CALLS"
DEF RANKING_PHONE_CALLS_DESC EQUS "<PARA>?"
DEF RANKING_PHONE_CALLS_UNIT EQUS " calls"
ELIF DEF(_LANG_D)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
DEF RANKING_PHONE_CALLS_DESC EQUS "<PARA>?"
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
DEF RANKING_PHONE_CALLS_DESC EQUS "<PARA>?"
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
DEF RANKING_PHONE_CALLS_DESC EQUS "<PARA>?"
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_PHONE_CALLS_NAME EQUS "?"
DEF RANKING_PHONE_CALLS_DESC EQUS "<PARA>?"
DEF RANKING_PHONE_CALLS_UNIT EQUS "?"
ENDC

; Ranking 27: Unused 2
DEF RANKING_UNUSED_2_ADDR EQUS "sTrainerRankingUnused2"
DEF RANKING_UNUSED_2_FMT  EQUS "3, 8"
DEF RANKING_UNUSED_2_SPACING EQU 1
IF DEF(_LANG_J)
DEF RANKING_UNUSED_2_NAME EQUS "?"
DEF RANKING_UNUSED_2_DESC EQUS "?"
DEF RANKING_UNUSED_2_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_UNUSED_2_NAME EQUS "?"
DEF RANKING_UNUSED_2_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_2_UNIT EQUS "?"
ELIF DEF(_LANG_D)
DEF RANKING_UNUSED_2_NAME EQUS "?"
DEF RANKING_UNUSED_2_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_2_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_UNUSED_2_NAME EQUS "?"
DEF RANKING_UNUSED_2_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_2_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_UNUSED_2_NAME EQUS "?"
DEF RANKING_UNUSED_2_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_2_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_UNUSED_2_NAME EQUS "?"
DEF RANKING_UNUSED_2_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_2_UNIT EQUS "?"
ENDC

; Ranking 28: Number of Colosseum battles
DEF RANKING_LINK_BATTLES_ADDR EQUS "sTrainerRankingLinkBattles"
DEF RANKING_LINK_BATTLES_FMT  EQUS "3, 7"
DEF RANKING_LINK_BATTLES_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
DEF RANKING_LINK_BATTLES_DESC EQUS "?"
DEF RANKING_LINK_BATTLES_UNIT EQUS "かい" ; a guess
ELIF DEF(_LANG_E)
DEF RANKING_LINK_BATTLES_NAME EQUS "COLOSSEUM BATTLES"
DEF RANKING_LINK_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_BATTLES_UNIT EQUS " battles"
ELIF DEF(_LANG_D)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
DEF RANKING_LINK_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
DEF RANKING_LINK_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
DEF RANKING_LINK_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_BATTLES_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_LINK_BATTLES_NAME EQUS "?"
DEF RANKING_LINK_BATTLES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_BATTLES_UNIT EQUS "?"
ENDC

; Ranking 29: Number of times players Pokémon used Splash
DEF RANKING_SPLASH_ADDR EQUS "sTrainerRankingSplash"
DEF RANKING_SPLASH_FMT  EQUS "3, 7"
DEF RANKING_SPLASH_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_SPLASH_NAME EQUS "?"
DEF RANKING_SPLASH_DESC EQUS "?"
DEF RANKING_SPLASH_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_SPLASH_NAME EQUS "USED SPLASH"
DEF RANKING_SPLASH_DESC EQUS "<PARA>?"
DEF RANKING_SPLASH_UNIT EQUS " times"
ELIF DEF(_LANG_D)
DEF RANKING_SPLASH_NAME EQUS "?"
DEF RANKING_SPLASH_DESC EQUS "<PARA>?"
DEF RANKING_SPLASH_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_SPLASH_NAME EQUS "?"
DEF RANKING_SPLASH_DESC EQUS "<PARA>?"
DEF RANKING_SPLASH_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_SPLASH_NAME EQUS "?"
DEF RANKING_SPLASH_DESC EQUS "<PARA>?"
DEF RANKING_SPLASH_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_SPLASH_NAME EQUS "?"
DEF RANKING_SPLASH_DESC EQUS "<PARA>?"
DEF RANKING_SPLASH_UNIT EQUS "?"
ENDC

; Ranking 30: Number of tree Pokémon encounters
; actually, it doesnt care about whether an encounter happened
; only that the player used headbutt on a tree
DEF RANKING_TREE_ENCOUNTERS_ADDR EQUS "sTrainerRankingTreeEncounters"
DEF RANKING_TREE_ENCOUNTERS_FMT  EQUS "3, 7"
DEF RANKING_TREE_ENCOUNTERS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "ずつきを　した　かいすう"
DEF RANKING_TREE_ENCOUNTERS_DESC EQUS "?"
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "USED HEADBUTT"
DEF RANKING_TREE_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS " times"
ELIF DEF(_LANG_D)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_TREE_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_TREE_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_TREE_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_TREE_ENCOUNTERS_NAME EQUS "?"
DEF RANKING_TREE_ENCOUNTERS_DESC EQUS "<PARA>?"
DEF RANKING_TREE_ENCOUNTERS_UNIT EQUS "?"
ENDC

; Ranking 31: Unused 3
DEF RANKING_UNUSED_3_ADDR EQUS "sTrainerRankingUnused3"
DEF RANKING_UNUSED_3_FMT  EQUS "3, 8"
DEF RANKING_UNUSED_3_SPACING EQU 1
IF DEF(_LANG_J)
DEF RANKING_UNUSED_3_NAME EQUS "?"
DEF RANKING_UNUSED_3_DESC EQUS "?"
DEF RANKING_UNUSED_3_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_UNUSED_3_NAME EQUS "?"
DEF RANKING_UNUSED_3_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_3_UNIT EQUS "?"
ELIF DEF(_LANG_D)
DEF RANKING_UNUSED_3_NAME EQUS "?"
DEF RANKING_UNUSED_3_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_3_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_UNUSED_3_NAME EQUS "?"
DEF RANKING_UNUSED_3_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_3_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_UNUSED_3_NAME EQUS "?"
DEF RANKING_UNUSED_3_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_3_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_UNUSED_3_NAME EQUS "?"
DEF RANKING_UNUSED_3_DESC EQUS "<PARA>?"
DEF RANKING_UNUSED_3_UNIT EQUS "?"
ENDC

; Ranking 32: Number of Colosseum wins
DEF RANKING_LINK_WINS_ADDR EQUS "sTrainerRankingColosseumWins"
DEF RANKING_LINK_WINS_FMT  EQUS "3, 7"
DEF RANKING_LINK_WINS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_LINK_WINS_NAME EQUS "コロシアムで　かった　かいすう"
DEF RANKING_LINK_WINS_DESC EQUS "?"
DEF RANKING_LINK_WINS_UNIT EQUS "かい"
ELIF DEF(_LANG_E)
DEF RANKING_LINK_WINS_NAME EQUS "COLOSSEUM WINS"
DEF RANKING_LINK_WINS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_WINS_UNIT EQUS " wins"
ELIF DEF(_LANG_D)
DEF RANKING_LINK_WINS_NAME EQUS "?"
DEF RANKING_LINK_WINS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_WINS_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_LINK_WINS_NAME EQUS "?"
DEF RANKING_LINK_WINS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_WINS_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_LINK_WINS_NAME EQUS "?"
DEF RANKING_LINK_WINS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_WINS_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_LINK_WINS_NAME EQUS "?"
DEF RANKING_LINK_WINS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_WINS_UNIT EQUS "?"
ENDC

; Ranking 33: Number of Colosseum losses
DEF RANKING_LINK_LOSSES_ADDR EQUS "sTrainerRankingColosseumLosses"
DEF RANKING_LINK_LOSSES_FMT  EQUS "3, 7"
DEF RANKING_LINK_LOSSES_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
DEF RANKING_LINK_LOSSES_DESC EQUS "?"
DEF RANKING_LINK_LOSSES_UNIT EQUS "かい" ; a guess
ELIF DEF(_LANG_E)
DEF RANKING_LINK_LOSSES_NAME EQUS "COLOSSEUM LOSSES"
DEF RANKING_LINK_LOSSES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_LOSSES_UNIT EQUS " losses"
ELIF DEF(_LANG_D)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
DEF RANKING_LINK_LOSSES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_LOSSES_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
DEF RANKING_LINK_LOSSES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_LOSSES_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
DEF RANKING_LINK_LOSSES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_LOSSES_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_LINK_LOSSES_NAME EQUS "?"
DEF RANKING_LINK_LOSSES_DESC EQUS "<PARA>?"
DEF RANKING_LINK_LOSSES_UNIT EQUS "?"
ENDC

; Ranking 34: Number of Colosseum ties
DEF RANKING_LINK_DRAWS_ADDR EQUS "sTrainerRankingColosseumDraws"
DEF RANKING_LINK_DRAWS_FMT  EQUS "3, 7"
DEF RANKING_LINK_DRAWS_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
DEF RANKING_LINK_DRAWS_DESC EQUS "?"
DEF RANKING_LINK_DRAWS_UNIT EQUS "かい" ; a guess
ELIF DEF(_LANG_E)
DEF RANKING_LINK_DRAWS_NAME EQUS "COLOSSEUM DRAWS"
DEF RANKING_LINK_DRAWS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_DRAWS_UNIT EQUS " draws"
ELIF DEF(_LANG_D)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
DEF RANKING_LINK_DRAWS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_DRAWS_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
DEF RANKING_LINK_DRAWS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_DRAWS_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
DEF RANKING_LINK_DRAWS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_DRAWS_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_LINK_DRAWS_NAME EQUS "?"
DEF RANKING_LINK_DRAWS_DESC EQUS "<PARA>?"
DEF RANKING_LINK_DRAWS_UNIT EQUS "?"
ENDC

; Ranking 35: Number of times players Pokémon used SelfDestruct or Explosion
DEF RANKING_SELFDESTRUCT_ADDR EQUS "sTrainerRankingSelfdestruct"
DEF RANKING_SELFDESTRUCT_FMT  EQUS "3, 7"
DEF RANKING_SELFDESTRUCT_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
DEF RANKING_SELFDESTRUCT_DESC EQUS "?"
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_SELFDESTRUCT_NAME EQUS "USED FAINTING MOVE"
DEF RANKING_SELFDESTRUCT_DESC EQUS "<PARA>?"
DEF RANKING_SELFDESTRUCT_UNIT EQUS " times"
ELIF DEF(_LANG_D)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
DEF RANKING_SELFDESTRUCT_DESC EQUS "<PARA>?"
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
DEF RANKING_SELFDESTRUCT_DESC EQUS "<PARA>?"
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
DEF RANKING_SELFDESTRUCT_DESC EQUS "<PARA>?"
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_SELFDESTRUCT_NAME EQUS "?"
DEF RANKING_SELFDESTRUCT_DESC EQUS "<PARA>?"
DEF RANKING_SELFDESTRUCT_UNIT EQUS "?"
ENDC

; Ranking 36: Current streak of consecutive slot machine wins
DEF RANKING_CURRENT_SLOTS_STREAK_ADDR EQUS "sTrainerRankingCurrentSlotsStreak"
DEF RANKING_CURRENT_SLOTS_STREAK_FMT  EQUS "2, 5"
DEF RANKING_CURRENT_SLOTS_STREAK_SPACING EQU 2
IF DEF(_LANG_J)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_CURRENT_SLOTS_STREAK_DESC EQUS "?"
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "SLOTS WIN STREAK"
DEF RANKING_CURRENT_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS " wins"
ELIF DEF(_LANG_D)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_CURRENT_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_CURRENT_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_CURRENT_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_CURRENT_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_CURRENT_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_CURRENT_SLOTS_STREAK_UNIT EQUS "?"
ENDC

; Ranking 37: Longest streak of consecutive slot machine wins
DEF RANKING_LONGEST_SLOTS_STREAK_ADDR EQUS "sTrainerRankingLongestSlotsStreak"
DEF RANKING_LONGEST_SLOTS_STREAK_FMT  EQUS "2, 5"
DEF RANKING_LONGEST_SLOTS_STREAK_SPACING EQU 2
IF DEF(_LANG_J)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_LONGEST_SLOTS_STREAK_DESC EQUS "?"
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "BEST SLOTS STREAK" ; TODO: confirm this name is ok
DEF RANKING_LONGEST_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS " wins"
ELIF DEF(_LANG_D)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_LONGEST_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_LONGEST_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_LONGEST_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_LONGEST_SLOTS_STREAK_NAME EQUS "?"
DEF RANKING_LONGEST_SLOTS_STREAK_DESC EQUS "<PARA>?"
DEF RANKING_LONGEST_SLOTS_STREAK_UNIT EQUS "?"
ENDC

; Ranking 38: Total coins won from slot machines
DEF RANKING_COINS_EARNED_ADDR EQUS "sTrainerRankingTotalSlotsPayouts"
DEF RANKING_COINS_EARNED_FMT  EQUS "4, 9"
DEF RANKING_COINS_EARNED_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
DEF RANKING_COINS_EARNED_DESC EQUS "?"
DEF RANKING_COINS_EARNED_UNIT EQUS "?"
ELIF DEF(_LANG_E)
DEF RANKING_COINS_EARNED_NAME EQUS "SLOT COINS WON"
DEF RANKING_COINS_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_COINS_EARNED_UNIT EQUS " coins"
DEF RANKING_COINS_EARNED_SPACING EQU -1
ELIF DEF(_LANG_D)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
DEF RANKING_COINS_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_COINS_EARNED_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
DEF RANKING_COINS_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_COINS_EARNED_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
DEF RANKING_COINS_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_COINS_EARNED_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_COINS_EARNED_NAME EQUS "?"
DEF RANKING_COINS_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_COINS_EARNED_UNIT EQUS "?"
ENDC

; Ranking 39: Total money earned from battles (including Pay Day)
DEF RANKING_MONEY_EARNED_ADDR EQUS "sTrainerRankingTotalBattlePayouts"
DEF RANKING_MONEY_EARNED_FMT  EQUS "4, 9"
DEF RANKING_MONEY_EARNED_SPACING EQU 0
IF DEF(_LANG_J)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
DEF RANKING_MONEY_EARNED_DESC EQUS "?"
DEF RANKING_MONEY_EARNED_UNIT EQUS ""
ELIF DEF(_LANG_E)
DEF RANKING_MONEY_EARNED_NAME EQUS "MONEY EARNED"
DEF RANKING_MONEY_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_MONEY_EARNED_UNIT EQUS "¥"
ELIF DEF(_LANG_D)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
DEF RANKING_MONEY_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_MONEY_EARNED_UNIT EQUS "?"
ELIF DEF(_LANG_F)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
DEF RANKING_MONEY_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_MONEY_EARNED_UNIT EQUS "?"
ELIF DEF(_LANG_I)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
DEF RANKING_MONEY_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_MONEY_EARNED_UNIT EQUS "?"
ELIF DEF(_LANG_S)
DEF RANKING_MONEY_EARNED_NAME EQUS "?"
DEF RANKING_MONEY_EARNED_DESC EQUS "<PARA>?"
DEF RANKING_MONEY_EARNED_UNIT EQUS "?"
ENDC

; Ranking 40: Largest Magikarp measured
DEF RANKING_LONGEST_MAGIKARP_ADDR EQUS "sTrainerRankingLongestMagikarp"
DEF RANKING_LONGEST_MAGIKARP_ADDR_LO EQUS "sTrainerRankingLongestMagikarpLow"
DEF RANKING_LONGEST_MAGIKARP_SPACING EQU 1
IF DEF(_LANG_J)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "つった　コイキング<NO>おおきさ"
DEF RANKING_LONGEST_MAGIKARP_FULLNAME EQUS "コイキング<NO>おおきさ"
DEF RANKING_LONGEST_MAGIKARP_DESC EQUS "いかりのみずうみ<NI>いる<CONT>つりめいじん<NI>はか<TTE>もらった<CONT>コイキング<NO>うち　いちばん<CONT>おおきかった　もので　きそいます"
DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \"<DOT>\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS "センチ"
ELIF DEF(_LANG_E)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "LARGEST MAGIKARP"
DEF RANKING_LONGEST_MAGIKARP_DESC EQUS "<PARA>The size of the<LINE>largest MAGIKARP<CONT>measured by the<CONT>FISHING GURU at<CONT>the LAKE OF RAGE."
;DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \"<DOT>\""
DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "1, 3, 0\nnts_end\ndb \"'\"\nnts_start\nnts_ranking_number $0015, 1, 2, 0"
DEF RANKING_LONGEST_MAGIKARP_FMT_PLAYER EQUS "1, 3, 0\nnts_end\ndb \"'\"\nnts_start\nnts_number {RANKING_LONGEST_MAGIKARP_ADDR_LO}, 1, 2, 0"
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS "”"
ELIF DEF(_LANG_D)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "GRÖSSTES KARPADOR"
DEF RANKING_LONGEST_MAGIKARP_DESC EQUS "<PARA>Das größte<LINE>KARPADOR, das<CONT>vom PROFI-ANGLER<CONT>am SEE DES ZORNS<CONT>gemessen wurde."
DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS " cm"
ELIF DEF(_LANG_F)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "GIGA MAGICARPE"
DEF RANKING_LONGEST_MAGIKARP_DESC EQUS "<PARA>La taille du plus<LINE>grand MAGICARPE<CONT>mesuré par le<CONT>MAITRE PECHEUR<CONT>au LAC COLERE."
DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS " cm"
ELIF DEF(_LANG_I)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "MAGIKARP PIÙ GR."
DEF RANKING_LONGEST_MAGIKARP_FULLNAME EQUS "IL MAGIKARP PIÙ<LINE>GROSSO"
DEF RANKING_LONGEST_MAGIKARP_DESC EQUS "<PARA>Le dimensioni del<LINE>MAGIKARP più<CONT>grosso per il GURU<CONT>PESCATORE al<CONT>LAGO D'IRA."
DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS " cm"
ELIF DEF(_LANG_S)
DEF RANKING_LONGEST_MAGIKARP_NAME EQUS "?"
DEF RANKING_LONGEST_MAGIKARP_DESC EQUS "<PARA>?"
DEF RANKING_LONGEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_LONGEST_MAGIKARP_UNIT EQUS "?"
ENDC

; Ranking 41: Smallest Magikarp measured
DEF RANKING_SHORTEST_MAGIKARP_ADDR EQUS "sTrainerRankingShortestMagikarp"
DEF RANKING_SHORTEST_MAGIKARP_ADDR_LO EQUS "sTrainerRankingShortestMagikarpLow"
DEF RANKING_SHORTEST_MAGIKARP_SPACING EQU 1
IF DEF(_LANG_J)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
DEF RANKING_SHORTEST_MAGIKARP_DESC EQUS "?"
DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \"<DOT>\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS "センチ"
ELIF DEF(_LANG_E)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "SMALLEST MAGIKARP"
DEF RANKING_SHORTEST_MAGIKARP_DESC EQUS "<PARA>?"
;DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \"<DOT>\""
;DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS " cm."
DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "1, 3\nnts_end\ndb \"'\"\nnts_start\nnts_ranking_number $0015, 1, 2"
DEF RANKING_SHORTEST_MAGIKARP_FMT_PLAYER EQUS "1, 3\nnts_end\ndb \"'\"\nnts_start\nnts_number {RANKING_SHORTEST_MAGIKARP_ADDR_LO}, 1, 2"
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS "”"
ELIF DEF(_LANG_D)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
DEF RANKING_SHORTEST_MAGIKARP_DESC EQUS "<PARA>?"
DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS " cm"
ELIF DEF(_LANG_F)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
DEF RANKING_SHORTEST_MAGIKARP_DESC EQUS "<PARA>?"
DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS " cm"
ELIF DEF(_LANG_I)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
DEF RANKING_SHORTEST_MAGIKARP_DESC EQUS "<PARA>?"
DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS " cm"
ELIF DEF(_LANG_S)
DEF RANKING_SHORTEST_MAGIKARP_NAME EQUS "?"
DEF RANKING_SHORTEST_MAGIKARP_DESC EQUS "<PARA>?"
DEF RANKING_SHORTEST_MAGIKARP_FMT  EQUS "PRINTNUM_LEADINGZEROS | 2, 4, 5, 4, \",\""
DEF RANKING_SHORTEST_MAGIKARP_UNIT EQUS "?"
ENDC

; Ranking 42: Bug-Catching Contest high score
DEF RANKING_BUG_CONTEST_SCORE_ADDR EQUS "sTrainerRankingBugContestScore"
DEF RANKING_BUG_CONTEST_SCORE_FMT  EQUS "2, 5"
DEF RANKING_BUG_CONTEST_SCORE_SPACING EQU 1
IF DEF(_LANG_J)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "むしとりたいかい　こうとくてん"
DEF RANKING_BUG_CONTEST_SCORE_DESC EQUS "しぜんこうえんで　おこなわれる<CONT>むしとりたいかいで　これまでに<CONT>とった　いちばん　たかい<CONT>てんすうで　きそいます"
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS "てん"
ELIF DEF(_LANG_E)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "BUG-CATCHING"
DEF RANKING_BUG_CONTEST_SCORE_DESC EQUS "<PARA>The highest score<LINE>obtained at the<CONT>BUG-CATCHING Con-<CONT>test held in the<CONT>NATIONAL PARK."
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " points"
ELIF DEF(_LANG_D)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "KÄFER-TURNIER"
DEF RANKING_BUG_CONTEST_SCORE_DESC EQUS "<PARA>Die höchste Punkt-<LINE>zahl beim KÄFER-<CONT>TURNIER im<CONT>NATIONALPARK."
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " Punkte"
ELIF DEF(_LANG_F)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "CAPTURE D'INSECTE"
DEF RANKING_BUG_CONTEST_SCORE_DESC EQUS "<PARA>Le plus haut score<LINE>obtenu au Concours<CONT>de Capture d'inse-<CONT>cte qui se déroule<CONT>au PARC NATUREL."
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " points"
ELIF DEF(_LANG_I)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "GARA PIGLIAMOSCHE"
DEF RANKING_BUG_CONTEST_SCORE_DESC EQUS "<PARA>Il punteggio più<LINE>alto ottenuto alla<CONT>GARA PIGLIAMOSCHE<CONT>tenuta nel PARCO<CONT>NAZIONALE."
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS " punti"
ELIF DEF(_LANG_S)
DEF RANKING_BUG_CONTEST_SCORE_NAME EQUS "?"
DEF RANKING_BUG_CONTEST_SCORE_DESC EQUS "<PARA>?"
DEF RANKING_BUG_CONTEST_SCORE_UNIT EQUS "?"
ENDC