INCLUDE "pokecrystal/macros/asserts.asm"
INCLUDE "pokecrystal/macros/const.asm"
INCLUDE "pokecrystal/macros/predef.asm"
INCLUDE "pokecrystal/macros/farcall.asm"
INCLUDE "pokecrystal/macros/data.asm"
INCLUDE "pokecrystal/macros/code.asm"
INCLUDE "pokecrystal/macros/gfx.asm"
INCLUDE "pokecrystal/macros/coords.asm"
;INCLUDE "macros/vc.asm"

;INCLUDE "macros/scripts/audio.asm"
;INCLUDE "macros/scripts/maps.asm"
;INCLUDE "macros/scripts/events.asm"
INCLUDE "pokecrystal/macros/scripts/text.asm"
;INCLUDE "macros/scripts/movement.asm"
;INCLUDE "macros/scripts/battle_commands.asm"
;INCLUDE "macros/scripts/battle_anims.asm"
INCLUDE "pokecrystal/macros/scripts/oam_anims.asm"
INCLUDE "pokecrystal/macros/scripts/pic_anims.asm"

;INCLUDE "macros/legacy.asm"
